# SAPE IA 2.0 — Regras clínicas de pré-natal
# Recuperadas e normalizadas a partir do acervo do projeto.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Início tardio do pré-natal',
  'diagnostico': {'codigo': None, 'termo': 'Adesão ao cuidado prejudicada'},
  'resultado': {'codigo': None, 'termo': 'Adesão ao cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Organizar plano de seguimento do pré-natal'},
  'prioridade': 'Alta',
  'fundamentacao': 'O início tardio do pré-natal dificulta o rastreamento oportuno de fatores de risco, o vínculo com '
                   'a equipe e a prevenção de agravos maternos e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar agenda conforme realidade territorial e familiar da gestante.'],
                    'repadronizacao': ['Reorganizar plano de cuidado garantindo consultas mínimas e exames '
                                       'essenciais.']},
  'referencias': ['Ministério da Saúde. Atenção ao Pré-Natal de Baixo Risco.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural do Cuidado.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Gestante faltosa',
  'diagnostico': {'codigo': None, 'termo': 'Continuidade do cuidado prejudicada'},
  'resultado': {'codigo': None, 'termo': 'Continuidade do cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Realizar busca ativa da gestante'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência nas consultas compromete a vigilância clínica materna e fetal e aumenta o risco de '
                   'perda de oportunidades diagnósticas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar barreiras familiares, culturais, econômicas e territoriais.'],
                    'repadronizacao': ['Planejar busca ativa juntamente com ACS e equipe multiprofissional.']},
  'referencias': ['PNAB.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Área descoberta pela ESF',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Acesso ao cuidado melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Organizar seguimento do pré-natal'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de cobertura regular da ESF compromete a longitudinalidade do cuidado.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar lideranças comunitárias e formas locais de comunicação.'],
                    'repadronizacao': ['Articular plano alternativo de acompanhamento pela UBS.']},
  'referencias': ['PNAB.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Longa distância até a UBS',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Acesso ao cuidado melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Planejar retorno conforme possibilidade de deslocamento'},
  'prioridade': 'Alta',
  'fundamentacao': 'Barreiras geográficas dificultam a continuidade do acompanhamento pré-natal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar cronograma conforme logística territorial.'],
                    'repadronizacao': ['Concentrar exames e procedimentos na mesma consulta.']},
  'referencias': ['PNAB.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Transporte fluvial',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Continuidade do cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Planejar consultas conforme logística fluvial'},
  'prioridade': 'Alta',
  'fundamentacao': 'A logística fluvial interfere no acesso oportuno ao cuidado.',
  'transcultural': {'preservacao': ['Reconhecer o modo de vida ribeirinho.'],
                    'acomodacao': ['Adequar consultas conforme disponibilidade das embarcações.'],
                    'repadronizacao': ['Criar plano para situações de urgência obstétrica.']},
  'referencias': ['Leininger.', 'PNAB.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Início tardio do pré-natal',
  'diagnostico': {'codigo': None, 'termo': 'Adesão ao cuidado prejudicada'},
  'resultado': {'codigo': None, 'termo': 'Adesão ao cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Organizar plano de seguimento do pré-natal'},
  'prioridade': 'Alta',
  'fundamentacao': 'O início tardio do pré-natal dificulta o rastreamento oportuno de fatores de risco, o vínculo com '
                   'a equipe e a prevenção de agravos maternos e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar agenda conforme realidade territorial e familiar da gestante.'],
                    'repadronizacao': ['Reorganizar plano de cuidado garantindo consultas mínimas e exames '
                                       'essenciais.']},
  'referencias': ['Ministério da Saúde. Atenção ao Pré-Natal de Baixo Risco.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural do Cuidado.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Gestante faltosa',
  'diagnostico': {'codigo': None, 'termo': 'Continuidade do cuidado prejudicada'},
  'resultado': {'codigo': None, 'termo': 'Continuidade do cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Realizar busca ativa da gestante'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência nas consultas compromete a vigilância clínica materna e fetal e aumenta o risco de '
                   'perda de oportunidades diagnósticas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar barreiras familiares, culturais, econômicas e territoriais.'],
                    'repadronizacao': ['Planejar busca ativa juntamente com ACS e equipe multiprofissional.']},
  'referencias': ['PNAB.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Área descoberta pela ESF',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Acesso ao cuidado melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Organizar seguimento do pré-natal'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de cobertura regular da ESF compromete a longitudinalidade do cuidado.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar lideranças comunitárias e formas locais de comunicação.'],
                    'repadronizacao': ['Articular plano alternativo de acompanhamento pela UBS.']},
  'referencias': ['PNAB.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Longa distância até a UBS',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Acesso ao cuidado melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Planejar retorno conforme possibilidade de deslocamento'},
  'prioridade': 'Alta',
  'fundamentacao': 'Barreiras geográficas dificultam a continuidade do acompanhamento pré-natal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar cronograma conforme logística territorial.'],
                    'repadronizacao': ['Concentrar exames e procedimentos na mesma consulta.']},
  'referencias': ['PNAB.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Transporte fluvial',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Continuidade do cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Planejar consultas conforme logística fluvial'},
  'prioridade': 'Alta',
  'fundamentacao': 'A logística fluvial interfere no acesso oportuno ao cuidado.',
  'transcultural': {'preservacao': ['Reconhecer o modo de vida ribeirinho.'],
                    'acomodacao': ['Adequar consultas conforme disponibilidade das embarcações.'],
                    'repadronizacao': ['Criar plano para situações de urgência obstétrica.']},
  'referencias': ['Leininger.', 'PNAB.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Início tardio do pré-natal',
  'diagnostico': {'codigo': None, 'termo': 'Adesão ao cuidado prejudicada'},
  'resultado': {'codigo': None, 'termo': 'Adesão ao cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Organizar plano de seguimento do pré-natal'},
  'prioridade': 'Alta',
  'fundamentacao': 'O início tardio do pré-natal dificulta o rastreamento oportuno de fatores de risco, o vínculo com '
                   'a equipe e a prevenção de agravos maternos e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar agenda conforme realidade territorial e familiar da gestante.'],
                    'repadronizacao': ['Reorganizar plano de cuidado garantindo consultas mínimas e exames '
                                       'essenciais.']},
  'referencias': ['Ministério da Saúde. Atenção ao Pré-Natal de Baixo Risco.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural do Cuidado.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Gestante faltosa',
  'diagnostico': {'codigo': None, 'termo': 'Continuidade do cuidado prejudicada'},
  'resultado': {'codigo': None, 'termo': 'Continuidade do cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Realizar busca ativa da gestante'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência nas consultas compromete a vigilância clínica materna e fetal e aumenta o risco de '
                   'perda de oportunidades diagnósticas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar barreiras familiares, culturais, econômicas e territoriais.'],
                    'repadronizacao': ['Planejar busca ativa juntamente com ACS e equipe multiprofissional.']},
  'referencias': ['PNAB.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Área descoberta pela ESF',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Acesso ao cuidado melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Organizar seguimento do pré-natal'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de cobertura regular da ESF compromete a longitudinalidade do cuidado.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar lideranças comunitárias e formas locais de comunicação.'],
                    'repadronizacao': ['Articular plano alternativo de acompanhamento pela UBS.']},
  'referencias': ['PNAB.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Longa distância até a UBS',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Acesso ao cuidado melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Planejar retorno conforme possibilidade de deslocamento'},
  'prioridade': 'Alta',
  'fundamentacao': 'Barreiras geográficas dificultam a continuidade do acompanhamento pré-natal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar cronograma conforme logística territorial.'],
                    'repadronizacao': ['Concentrar exames e procedimentos na mesma consulta.']},
  'referencias': ['PNAB.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Transporte fluvial',
  'diagnostico': {'codigo': None, 'termo': 'Acesso ao serviço de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Continuidade do cuidado melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Planejar consultas conforme logística fluvial'},
  'prioridade': 'Alta',
  'fundamentacao': 'A logística fluvial interfere no acesso oportuno ao cuidado.',
  'transcultural': {'preservacao': ['Reconhecer o modo de vida ribeirinho.'],
                    'acomodacao': ['Adequar consultas conforme disponibilidade das embarcações.'],
                    'repadronizacao': ['Criar plano para situações de urgência obstétrica.']},
  'referencias': ['Leininger.', 'PNAB.']}]
