# SAPE IA 2.0 — Regras clínicas de pré-natal
# Recuperadas e normalizadas a partir do acervo do projeto.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Hipertensão arterial',
  'diagnostico': {'codigo': None, 'termo': 'Pressão arterial alterada'},
  'resultado': {'codigo': None, 'termo': 'Pressão arterial controlada'},
  'intervencao': {'codigo': None, 'termo': 'Monitorar pressão arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Pressão arterial elevada na gestação exige avaliação de risco para síndromes hipertensivas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar monitoramento conforme acesso da gestante ao serviço.'],
                    'repadronizacao': ['Criar plano de urgência para sinais de pré-eclâmpsia.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Proteinúria',
  'diagnostico': {'codigo': None, 'termo': 'Risco de condição hipertensiva na gestação'},
  'resultado': {'codigo': None, 'termo': 'Risco reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Avaliar sinais de gravidade'},
  'prioridade': 'Alta',
  'fundamentacao': 'Proteinúria associada à hipertensão pode indicar pré-eclâmpsia.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Orientar sinais de alerta com linguagem adequada ao contexto cultural.'],
                    'repadronizacao': ['Encaminhar conforme risco e organizar transporte se necessário.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Cefaleia persistente',
  'diagnostico': {'codigo': None, 'termo': 'Risco de condição hipertensiva na gestação'},
  'resultado': {'codigo': None, 'termo': 'Segurança materno-fetal preservada'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para avaliação conforme protocolo de risco gestacional'},
  'prioridade': 'Alta',
  'fundamentacao': 'Cefaleia persistente pode ser sinal de gravidade em síndromes hipertensivas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Verificar práticas locais de autocuidado já utilizadas.'],
                    'repadronizacao': ['Orientar procura imediata do serviço diante de piora ou sinais associados.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Escotomas visuais',
  'diagnostico': {'codigo': None, 'termo': 'Risco de condição hipertensiva na gestação'},
  'resultado': {'codigo': None, 'termo': 'Segurança materno-fetal preservada'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para avaliação imediata'},
  'prioridade': 'Alta',
  'fundamentacao': 'Alterações visuais na gestação são sinais de alerta para agravamento hipertensivo.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Explicar a gravidade usando linguagem simples.'],
                    'repadronizacao': ['Priorizar remoção/encaminhamento mesmo diante de barreiras territoriais.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Edema importante',
  'diagnostico': {'codigo': None, 'termo': 'Risco de pré-eclâmpsia'},
  'resultado': {'codigo': None, 'termo': 'Risco reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Avaliar pressão arterial e proteinúria'},
  'prioridade': 'Alta',
  'fundamentacao': 'Edema importante associado a outros sinais pode indicar agravamento clínico.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar percepção cultural sobre edema na gestação.'],
                    'repadronizacao': ['Reforçar sinais de alerta e necessidade de avaliação imediata.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Glicemia alterada',
  'diagnostico': {'codigo': None, 'termo': 'Risco de glicemia alterada'},
  'resultado': {'codigo': None, 'termo': 'Glicemia controlada'},
  'intervencao': {'codigo': None, 'termo': 'Orientar acompanhamento glicêmico conforme protocolo'},
  'prioridade': 'Alta',
  'fundamentacao': 'Alterações glicêmicas na gestação exigem rastreamento e acompanhamento de diabetes gestacional.',
  'transcultural': {'preservacao': ['Reconhecer hábitos alimentares regionais.'],
                    'acomodacao': ['Adaptar orientação alimentar à disponibilidade local de alimentos.'],
                    'repadronizacao': ['Reorganizar plano alimentar quando houver risco metabólico.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Diabetes gestacional',
  'diagnostico': {'codigo': None, 'termo': 'Glicemia alterada'},
  'resultado': {'codigo': None, 'termo': 'Glicemia controlada'},
  'intervencao': {'codigo': None, 'termo': 'Acompanhar controle glicêmico'},
  'prioridade': 'Alta',
  'fundamentacao': 'Diabetes gestacional requer acompanhamento contínuo para redução de riscos materno-fetais.',
  'transcultural': {'preservacao': ['Valorizar práticas alimentares seguras da família.'],
                    'acomodacao': ['Negociar mudanças alimentares possíveis no contexto socioeconômico.'],
                    'repadronizacao': ['Encaminhar e intensificar acompanhamento conforme risco.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Anemia',
  'diagnostico': {'codigo': None, 'termo': 'Hemoglobina diminuída'},
  'resultado': {'codigo': None, 'termo': 'Hemoglobina melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Orientar suplementação de ferro'},
  'prioridade': 'Média',
  'fundamentacao': 'Anemia gestacional pode comprometer o bem-estar materno-fetal e deve ser acompanhada.',
  'transcultural': {'preservacao': ['Considerar alimentos regionais ricos em ferro.'],
                    'acomodacao': ['Orientar alimentação conforme disponibilidade local.'],
                    'repadronizacao': ['Reforçar adesão à suplementação quando houver risco.']},
  'referencias': ['Ministério da Saúde.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Obesidade',
  'diagnostico': {'codigo': None, 'termo': 'Peso corporal aumentado'},
  'resultado': {'codigo': None, 'termo': 'Peso corporal adequado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar alimentação saudável'},
  'prioridade': 'Média',
  'fundamentacao': 'Obesidade na gestação aumenta risco de hipertensão, diabetes gestacional e complicações '
                   'obstétricas.',
  'transcultural': {'preservacao': ['Reconhecer hábitos alimentares familiares.'],
                    'acomodacao': ['Negociar mudanças possíveis sem desconsiderar cultura alimentar.'],
                    'repadronizacao': ['Reorganizar plano alimentar e atividade física conforme risco.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Baixo peso',
  'diagnostico': {'codigo': None, 'termo': 'Peso corporal diminuído'},
  'resultado': {'codigo': None, 'termo': 'Estado nutricional melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar alimentação adequada'},
  'prioridade': 'Média',
  'fundamentacao': 'Baixo peso gestacional pode estar associado a vulnerabilidade nutricional e risco fetal.',
  'transcultural': {'preservacao': ['Considerar alimentos culturalmente aceitos.'],
                    'acomodacao': ['Ajustar plano alimentar à renda e disponibilidade local.'],
                    'repadronizacao': ['Articular apoio alimentar quando houver insegurança alimentar.']},
  'referencias': ['Ministério da Saúde.', 'Leininger.', 'PNAB.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Tabagismo',
  'diagnostico': {'codigo': None, 'termo': 'Comportamento de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Comportamento de saúde melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar cessação do tabagismo'},
  'prioridade': 'Alta',
  'fundamentacao': 'Tabagismo na gestação aumenta risco de complicações maternas e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar contexto familiar e social do uso de tabaco.'],
                    'repadronizacao': ['Construir plano gradual de redução e cessação.']},
  'referencias': ['Ministério da Saúde.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Uso de álcool',
  'diagnostico': {'codigo': None, 'termo': 'Comportamento de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Comportamento de saúde melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar interrupção do uso de álcool'},
  'prioridade': 'Alta',
  'fundamentacao': 'O uso de álcool na gestação representa risco para o desenvolvimento fetal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Avaliar contexto social e familiar relacionado ao uso.'],
                    'repadronizacao': ['Encaminhar para rede de apoio quando houver uso persistente.']},
  'referencias': ['Ministério da Saúde.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Uso de drogas',
  'diagnostico': {'codigo': None, 'termo': 'Comportamento de saúde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Comportamento de saúde melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para cuidado compartilhado em saúde mental'},
  'prioridade': 'Alta',
  'fundamentacao': 'Uso de substâncias psicoativas na gestação exige cuidado multiprofissional e redução de danos.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Realizar escuta qualificada sem julgamento.'],
                    'repadronizacao': ['Articular rede de saúde mental, assistência social e pré-natal de alto '
                                       'risco.']},
  'referencias': ['Ministério da Saúde.', 'Rede de Atenção Psicossocial.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Idade materna menor que 15 anos',
  'diagnostico': {'codigo': None, 'termo': 'Risco materno-fetal aumentado'},
  'resultado': {'codigo': None, 'termo': 'Risco materno-fetal reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para acompanhamento de pré-natal de alto risco'},
  'prioridade': 'Alta',
  'fundamentacao': 'Gestação em adolescente muito jovem requer avaliação ampliada de risco clínico, social e familiar.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Avaliar apoio familiar, vínculo escolar e proteção social.'],
                    'repadronizacao': ['Acionar rede de proteção quando necessário.']},
  'referencias': ['Ministério da Saúde.', 'ECA.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Idade materna maior ou igual a 35 anos',
  'diagnostico': {'codigo': None, 'termo': 'Risco materno-fetal aumentado'},
  'resultado': {'codigo': None, 'termo': 'Risco materno-fetal reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Avaliar fatores de risco gestacional'},
  'prioridade': 'Média',
  'fundamentacao': 'Idade materna avançada pode estar associada a maior risco obstétrico e comorbidades.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar história reprodutiva, rede de apoio e expectativas familiares.'],
                    'repadronizacao': ['Intensificar acompanhamento se houver comorbidades.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'Leininger.']}]
