# SAPE IA 2.0 — Regras clínicas de pré-natal
# Revisadas e vinculadas a termos oficiais CIPE 2019.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Início tardio do pré-natal',
  'diagnostico': {'codigo': '10022155', 'termo': 'Não Adesão ao Regime Terapêutico'},
  'resultado': {'codigo': '10030205', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10032449', 'termo': 'Promover Adesão ao Regime'},
  'prioridade': 'Alta',
  'fundamentacao': 'O início tardio do pré-natal dificulta o rastreamento oportuno de fatores de risco, o vínculo com '
                   'a equipe e a prevenção de agravos maternos e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar agenda conforme realidade territorial e familiar da gestante.'],
                    'repadronizacao': ['Reorganizar plano de cuidado garantindo consultas mínimas e exames '
                                       'essenciais.']},
  'referencias': ['Ministério da Saúde. Atenção ao Pré-Natal de Baixo Risco.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural do Cuidado.'],
  'formulacao_clinica_original': {'diagnostico': 'Adesão ao cuidado prejudicada',
                                  'resultado': 'Adesão ao cuidado melhorada',
                                  'intervencao': 'Organizar plano de seguimento do pré-natal'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Gestante faltosa',
  'diagnostico': {'codigo': '10029759', 'termo': 'Problema de Continuidade do Cuidado'},
  'resultado': {'codigo': '10035507', 'termo': 'Continuidade do Cuidado, Eficaz'},
  'intervencao': {'codigo': '10006966', 'termo': 'Garantir (ou Assegurar) Continuidade de Cuidado'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência nas consultas compromete a vigilância clínica materna e fetal e aumenta o risco de '
                   'perda de oportunidades diagnósticas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar barreiras familiares, culturais, econômicas e territoriais.'],
                    'repadronizacao': ['Planejar busca ativa juntamente com ACS e equipe multiprofissional.']},
  'referencias': ['PNAB.', 'COFEN Resolução nº 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Continuidade do cuidado prejudicada',
                                  'resultado': 'Continuidade do cuidado melhorada',
                                  'intervencao': 'Realizar busca ativa da gestante'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Área descoberta pela ESF',
  'diagnostico': {'codigo': '10029759', 'termo': 'Problema de Continuidade do Cuidado'},
  'resultado': {'codigo': '10035507', 'termo': 'Continuidade do Cuidado, Eficaz'},
  'intervencao': {'codigo': '10038385', 'termo': 'Encaminhar para Serviço Comunitário'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de cobertura regular da ESF compromete a longitudinalidade do cuidado.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar lideranças comunitárias e formas locais de comunicação.'],
                    'repadronizacao': ['Articular plano alternativo de acompanhamento pela UBS.']},
  'referencias': ['PNAB.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Acesso ao cuidado melhorado',
                                  'intervencao': 'Organizar seguimento do pré-natal'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Longa distância até a UBS',
  'diagnostico': {'codigo': '10041323', 'termo': 'Falta de Acesso a Transporte'},
  'resultado': {'codigo': '10041310', 'termo': 'Acesso a Transporte'},
  'intervencao': {'codigo': '10024171', 'termo': 'Arranjar (Organizar) Serviço de Transporte'},
  'prioridade': 'Alta',
  'fundamentacao': 'Barreiras geográficas dificultam a continuidade do acompanhamento pré-natal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar cronograma conforme logística territorial.'],
                    'repadronizacao': ['Concentrar exames e procedimentos na mesma consulta.']},
  'referencias': ['PNAB.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Acesso ao cuidado melhorado',
                                  'intervencao': 'Planejar retorno conforme possibilidade de deslocamento'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Transporte fluvial',
  'diagnostico': {'codigo': '10041323', 'termo': 'Falta de Acesso a Transporte'},
  'resultado': {'codigo': '10041310', 'termo': 'Acesso a Transporte'},
  'intervencao': {'codigo': '10024171', 'termo': 'Arranjar (Organizar) Serviço de Transporte'},
  'prioridade': 'Alta',
  'fundamentacao': 'A logística fluvial interfere no acesso oportuno ao cuidado.',
  'transcultural': {'preservacao': ['Reconhecer o modo de vida ribeirinho.'],
                    'acomodacao': ['Adequar consultas conforme disponibilidade das embarcações.'],
                    'repadronizacao': ['Criar plano para situações de urgência obstétrica.']},
  'referencias': ['Leininger.', 'PNAB.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Continuidade do cuidado melhorada',
                                  'intervencao': 'Planejar consultas conforme logística fluvial'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Início tardio do pré-natal',
  'diagnostico': {'codigo': '10022155', 'termo': 'Não Adesão ao Regime Terapêutico'},
  'resultado': {'codigo': '10030205', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10032449', 'termo': 'Promover Adesão ao Regime'},
  'prioridade': 'Alta',
  'fundamentacao': 'O início tardio do pré-natal dificulta o rastreamento oportuno de fatores de risco, o vínculo com '
                   'a equipe e a prevenção de agravos maternos e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar agenda conforme realidade territorial e familiar da gestante.'],
                    'repadronizacao': ['Reorganizar plano de cuidado garantindo consultas mínimas e exames '
                                       'essenciais.']},
  'referencias': ['Ministério da Saúde. Atenção ao Pré-Natal de Baixo Risco.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural do Cuidado.'],
  'formulacao_clinica_original': {'diagnostico': 'Adesão ao cuidado prejudicada',
                                  'resultado': 'Adesão ao cuidado melhorada',
                                  'intervencao': 'Organizar plano de seguimento do pré-natal'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Gestante faltosa',
  'diagnostico': {'codigo': '10029759', 'termo': 'Problema de Continuidade do Cuidado'},
  'resultado': {'codigo': '10035507', 'termo': 'Continuidade do Cuidado, Eficaz'},
  'intervencao': {'codigo': '10006966', 'termo': 'Garantir (ou Assegurar) Continuidade de Cuidado'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência nas consultas compromete a vigilância clínica materna e fetal e aumenta o risco de '
                   'perda de oportunidades diagnósticas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar barreiras familiares, culturais, econômicas e territoriais.'],
                    'repadronizacao': ['Planejar busca ativa juntamente com ACS e equipe multiprofissional.']},
  'referencias': ['PNAB.', 'COFEN Resolução nº 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Continuidade do cuidado prejudicada',
                                  'resultado': 'Continuidade do cuidado melhorada',
                                  'intervencao': 'Realizar busca ativa da gestante'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Área descoberta pela ESF',
  'diagnostico': {'codigo': '10029759', 'termo': 'Problema de Continuidade do Cuidado'},
  'resultado': {'codigo': '10035507', 'termo': 'Continuidade do Cuidado, Eficaz'},
  'intervencao': {'codigo': '10038385', 'termo': 'Encaminhar para Serviço Comunitário'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de cobertura regular da ESF compromete a longitudinalidade do cuidado.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar lideranças comunitárias e formas locais de comunicação.'],
                    'repadronizacao': ['Articular plano alternativo de acompanhamento pela UBS.']},
  'referencias': ['PNAB.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Acesso ao cuidado melhorado',
                                  'intervencao': 'Organizar seguimento do pré-natal'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Longa distância até a UBS',
  'diagnostico': {'codigo': '10041323', 'termo': 'Falta de Acesso a Transporte'},
  'resultado': {'codigo': '10041310', 'termo': 'Acesso a Transporte'},
  'intervencao': {'codigo': '10024171', 'termo': 'Arranjar (Organizar) Serviço de Transporte'},
  'prioridade': 'Alta',
  'fundamentacao': 'Barreiras geográficas dificultam a continuidade do acompanhamento pré-natal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar cronograma conforme logística territorial.'],
                    'repadronizacao': ['Concentrar exames e procedimentos na mesma consulta.']},
  'referencias': ['PNAB.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Acesso ao cuidado melhorado',
                                  'intervencao': 'Planejar retorno conforme possibilidade de deslocamento'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Transporte fluvial',
  'diagnostico': {'codigo': '10041323', 'termo': 'Falta de Acesso a Transporte'},
  'resultado': {'codigo': '10041310', 'termo': 'Acesso a Transporte'},
  'intervencao': {'codigo': '10024171', 'termo': 'Arranjar (Organizar) Serviço de Transporte'},
  'prioridade': 'Alta',
  'fundamentacao': 'A logística fluvial interfere no acesso oportuno ao cuidado.',
  'transcultural': {'preservacao': ['Reconhecer o modo de vida ribeirinho.'],
                    'acomodacao': ['Adequar consultas conforme disponibilidade das embarcações.'],
                    'repadronizacao': ['Criar plano para situações de urgência obstétrica.']},
  'referencias': ['Leininger.', 'PNAB.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Continuidade do cuidado melhorada',
                                  'intervencao': 'Planejar consultas conforme logística fluvial'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Início tardio do pré-natal',
  'diagnostico': {'codigo': '10022155', 'termo': 'Não Adesão ao Regime Terapêutico'},
  'resultado': {'codigo': '10030205', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10032449', 'termo': 'Promover Adesão ao Regime'},
  'prioridade': 'Alta',
  'fundamentacao': 'O início tardio do pré-natal dificulta o rastreamento oportuno de fatores de risco, o vínculo com '
                   'a equipe e a prevenção de agravos maternos e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar agenda conforme realidade territorial e familiar da gestante.'],
                    'repadronizacao': ['Reorganizar plano de cuidado garantindo consultas mínimas e exames '
                                       'essenciais.']},
  'referencias': ['Ministério da Saúde. Atenção ao Pré-Natal de Baixo Risco.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural do Cuidado.'],
  'formulacao_clinica_original': {'diagnostico': 'Adesão ao cuidado prejudicada',
                                  'resultado': 'Adesão ao cuidado melhorada',
                                  'intervencao': 'Organizar plano de seguimento do pré-natal'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Gestante faltosa',
  'diagnostico': {'codigo': '10029759', 'termo': 'Problema de Continuidade do Cuidado'},
  'resultado': {'codigo': '10035507', 'termo': 'Continuidade do Cuidado, Eficaz'},
  'intervencao': {'codigo': '10006966', 'termo': 'Garantir (ou Assegurar) Continuidade de Cuidado'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência nas consultas compromete a vigilância clínica materna e fetal e aumenta o risco de '
                   'perda de oportunidades diagnósticas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar barreiras familiares, culturais, econômicas e territoriais.'],
                    'repadronizacao': ['Planejar busca ativa juntamente com ACS e equipe multiprofissional.']},
  'referencias': ['PNAB.', 'COFEN Resolução nº 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Continuidade do cuidado prejudicada',
                                  'resultado': 'Continuidade do cuidado melhorada',
                                  'intervencao': 'Realizar busca ativa da gestante'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Área descoberta pela ESF',
  'diagnostico': {'codigo': '10029759', 'termo': 'Problema de Continuidade do Cuidado'},
  'resultado': {'codigo': '10035507', 'termo': 'Continuidade do Cuidado, Eficaz'},
  'intervencao': {'codigo': '10038385', 'termo': 'Encaminhar para Serviço Comunitário'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de cobertura regular da ESF compromete a longitudinalidade do cuidado.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar lideranças comunitárias e formas locais de comunicação.'],
                    'repadronizacao': ['Articular plano alternativo de acompanhamento pela UBS.']},
  'referencias': ['PNAB.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Acesso ao cuidado melhorado',
                                  'intervencao': 'Organizar seguimento do pré-natal'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Longa distância até a UBS',
  'diagnostico': {'codigo': '10041323', 'termo': 'Falta de Acesso a Transporte'},
  'resultado': {'codigo': '10041310', 'termo': 'Acesso a Transporte'},
  'intervencao': {'codigo': '10024171', 'termo': 'Arranjar (Organizar) Serviço de Transporte'},
  'prioridade': 'Alta',
  'fundamentacao': 'Barreiras geográficas dificultam a continuidade do acompanhamento pré-natal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar cronograma conforme logística territorial.'],
                    'repadronizacao': ['Concentrar exames e procedimentos na mesma consulta.']},
  'referencias': ['PNAB.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Acesso ao cuidado melhorado',
                                  'intervencao': 'Planejar retorno conforme possibilidade de deslocamento'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Captação e vínculo',
  'achado_clinico': 'Transporte fluvial',
  'diagnostico': {'codigo': '10041323', 'termo': 'Falta de Acesso a Transporte'},
  'resultado': {'codigo': '10041310', 'termo': 'Acesso a Transporte'},
  'intervencao': {'codigo': '10024171', 'termo': 'Arranjar (Organizar) Serviço de Transporte'},
  'prioridade': 'Alta',
  'fundamentacao': 'A logística fluvial interfere no acesso oportuno ao cuidado.',
  'transcultural': {'preservacao': ['Reconhecer o modo de vida ribeirinho.'],
                    'acomodacao': ['Adequar consultas conforme disponibilidade das embarcações.'],
                    'repadronizacao': ['Criar plano para situações de urgência obstétrica.']},
  'referencias': ['Leininger.', 'PNAB.'],
  'formulacao_clinica_original': {'diagnostico': 'Acesso ao serviço de saúde prejudicado',
                                  'resultado': 'Continuidade do cuidado melhorada',
                                  'intervencao': 'Planejar consultas conforme logística fluvial'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'}]
