# SAPE IA 2.0 — Regras clínicas de pré-natal
# Revisadas e vinculadas a termos oficiais CIPE 2019.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Hipertensão arterial',
  'diagnostico': {'codigo': '10022954', 'termo': 'Pressão Arterial, Alterada'},
  'resultado': {'codigo': '10027647', 'termo': 'Pressão Arterial, nos Limites Normais'},
  'intervencao': {'codigo': '10032052', 'termo': 'Monitorar Pressão Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Pressão arterial elevada na gestação exige avaliação de risco para síndromes hipertensivas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar monitoramento conforme acesso da gestante ao serviço.'],
                    'repadronizacao': ['Criar plano de urgência para sinais de pré-eclâmpsia.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Pressão arterial alterada',
                                  'resultado': 'Pressão arterial controlada',
                                  'intervencao': 'Monitorar pressão arterial'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Proteinúria',
  'diagnostico': {'codigo': '10023225', 'termo': 'Risco de Complicações durante a Gestação (Gravidez)'},
  'resultado': {'codigo': '10042446', 'termo': 'Complicação durante a Gestação (Gravidez), Ausente'},
  'intervencao': {'codigo': '10032099', 'termo': 'Monitorar Resultado Laboratorial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Proteinúria associada à hipertensão pode indicar pré-eclâmpsia.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Orientar sinais de alerta com linguagem adequada ao contexto cultural.'],
                    'repadronizacao': ['Encaminhar conforme risco e organizar transporte se necessário.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco de condição hipertensiva na gestação',
                                  'resultado': 'Risco reduzido',
                                  'intervencao': 'Avaliar sinais de gravidade'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Cefaleia persistente',
  'diagnostico': {'codigo': '10023225', 'termo': 'Risco de Complicações durante a Gestação (Gravidez)'},
  'resultado': {'codigo': '10042446', 'termo': 'Complicação durante a Gestação (Gravidez), Ausente'},
  'intervencao': {'codigo': '10032567', 'termo': 'Encaminhar a Prestador (ou Provedor) de Cuidados de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Cefaleia persistente pode ser sinal de gravidade em síndromes hipertensivas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Verificar práticas locais de autocuidado já utilizadas.'],
                    'repadronizacao': ['Orientar procura imediata do serviço diante de piora ou sinais associados.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco de condição hipertensiva na gestação',
                                  'resultado': 'Segurança materno-fetal preservada',
                                  'intervencao': 'Encaminhar para avaliação conforme protocolo de risco gestacional'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Escotomas visuais',
  'diagnostico': {'codigo': '10023225', 'termo': 'Risco de Complicações durante a Gestação (Gravidez)'},
  'resultado': {'codigo': '10042446', 'termo': 'Complicação durante a Gestação (Gravidez), Ausente'},
  'intervencao': {'codigo': '10032567', 'termo': 'Encaminhar a Prestador (ou Provedor) de Cuidados de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Alterações visuais na gestação são sinais de alerta para agravamento hipertensivo.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Explicar a gravidade usando linguagem simples.'],
                    'repadronizacao': ['Priorizar remoção/encaminhamento mesmo diante de barreiras territoriais.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco de condição hipertensiva na gestação',
                                  'resultado': 'Segurança materno-fetal preservada',
                                  'intervencao': 'Encaminhar para avaliação imediata'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Edema importante',
  'diagnostico': {'codigo': '10023225', 'termo': 'Risco de Complicações durante a Gestação (Gravidez)'},
  'resultado': {'codigo': '10042446', 'termo': 'Complicação durante a Gestação (Gravidez), Ausente'},
  'intervencao': {'codigo': '10031996', 'termo': 'Medir (ou Verificar) Pressão Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Edema importante associado a outros sinais pode indicar agravamento clínico.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar percepção cultural sobre edema na gestação.'],
                    'repadronizacao': ['Reforçar sinais de alerta e necessidade de avaliação imediata.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco de pré-eclâmpsia',
                                  'resultado': 'Risco reduzido',
                                  'intervencao': 'Avaliar pressão arterial e proteinúria'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Glicemia alterada',
  'diagnostico': {'codigo': '10027550', 'termo': 'Hiperglicemia'},
  'resultado': {'codigo': '10033713', 'termo': 'Condição Endócrina, Eficaz'},
  'intervencao': {'codigo': '10032034', 'termo': 'Monitorar Glicose Sanguínea'},
  'prioridade': 'Alta',
  'fundamentacao': 'Alterações glicêmicas na gestação exigem rastreamento e acompanhamento de diabetes gestacional.',
  'transcultural': {'preservacao': ['Reconhecer hábitos alimentares regionais.'],
                    'acomodacao': ['Adaptar orientação alimentar à disponibilidade local de alimentos.'],
                    'repadronizacao': ['Reorganizar plano alimentar quando houver risco metabólico.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco de glicemia alterada',
                                  'resultado': 'Glicemia controlada',
                                  'intervencao': 'Orientar acompanhamento glicêmico conforme protocolo'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Diabetes gestacional',
  'diagnostico': {'codigo': '10027550', 'termo': 'Hiperglicemia'},
  'resultado': {'codigo': '10033713', 'termo': 'Condição Endócrina, Eficaz'},
  'intervencao': {'codigo': '10035286', 'termo': 'Gerenciar Hiperglicemia'},
  'prioridade': 'Alta',
  'fundamentacao': 'Diabetes gestacional requer acompanhamento contínuo para redução de riscos materno-fetais.',
  'transcultural': {'preservacao': ['Valorizar práticas alimentares seguras da família.'],
                    'acomodacao': ['Negociar mudanças alimentares possíveis no contexto socioeconômico.'],
                    'repadronizacao': ['Encaminhar e intensificar acompanhamento conforme risco.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Glicemia alterada',
                                  'resultado': 'Glicemia controlada',
                                  'intervencao': 'Acompanhar controle glicêmico'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Anemia',
  'diagnostico': {'codigo': '10025746', 'termo': 'Condição Nutricional, Prejudicada'},
  'resultado': {'codigo': '10035569', 'termo': 'Condição Nutricional, Melhorada'},
  'intervencao': {'codigo': '10037037', 'termo': 'Administrar Suplemento Nutricional'},
  'prioridade': 'Média',
  'fundamentacao': 'Anemia gestacional pode comprometer o bem-estar materno-fetal e deve ser acompanhada.',
  'transcultural': {'preservacao': ['Considerar alimentos regionais ricos em ferro.'],
                    'acomodacao': ['Orientar alimentação conforme disponibilidade local.'],
                    'repadronizacao': ['Reforçar adesão à suplementação quando houver risco.']},
  'referencias': ['Ministério da Saúde.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Hemoglobina diminuída',
                                  'resultado': 'Hemoglobina melhorada',
                                  'intervencao': 'Orientar suplementação de ferro'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Obesidade',
  'diagnostico': {'codigo': '10027300', 'termo': 'Sobrepeso'},
  'resultado': {'codigo': '10027392', 'termo': 'Peso, nos Limites Normais'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Média',
  'fundamentacao': 'Obesidade na gestação aumenta risco de hipertensão, diabetes gestacional e complicações '
                   'obstétricas.',
  'transcultural': {'preservacao': ['Reconhecer hábitos alimentares familiares.'],
                    'acomodacao': ['Negociar mudanças possíveis sem desconsiderar cultura alimentar.'],
                    'repadronizacao': ['Reorganizar plano alimentar e atividade física conforme risco.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Peso corporal aumentado',
                                  'resultado': 'Peso corporal adequado',
                                  'intervencao': 'Orientar alimentação saudável'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Baixo peso',
  'diagnostico': {'codigo': '10027316', 'termo': 'Baixo Peso'},
  'resultado': {'codigo': '10027392', 'termo': 'Peso, nos Limites Normais'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Média',
  'fundamentacao': 'Baixo peso gestacional pode estar associado a vulnerabilidade nutricional e risco fetal.',
  'transcultural': {'preservacao': ['Considerar alimentos culturalmente aceitos.'],
                    'acomodacao': ['Ajustar plano alimentar à renda e disponibilidade local.'],
                    'repadronizacao': ['Articular apoio alimentar quando houver insegurança alimentar.']},
  'referencias': ['Ministério da Saúde.', 'Leininger.', 'PNAB.'],
  'formulacao_clinica_original': {'diagnostico': 'Peso corporal diminuído',
                                  'resultado': 'Estado nutricional melhorado',
                                  'intervencao': 'Orientar alimentação adequada'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Tabagismo',
  'diagnostico': {'codigo': '10022247', 'termo': 'Abuso de Tabaco (ou de Fumo)'},
  'resultado': {'codigo': '10029147', 'termo': 'Abuso de Tabaco (ou de Fumo), Ausente'},
  'intervencao': {'codigo': '10031058', 'termo': 'Aconselhar sobre Tabagismo'},
  'prioridade': 'Alta',
  'fundamentacao': 'Tabagismo na gestação aumenta risco de complicações maternas e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar contexto familiar e social do uso de tabaco.'],
                    'repadronizacao': ['Construir plano gradual de redução e cessação.']},
  'referencias': ['Ministério da Saúde.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Comportamento de saúde prejudicado',
                                  'resultado': 'Comportamento de saúde melhorado',
                                  'intervencao': 'Orientar cessação do tabagismo'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Uso de álcool',
  'diagnostico': {'codigo': '10022234', 'termo': 'Abuso de Álcool (ou Alcoolismo)'},
  'resultado': {'codigo': '10028765', 'termo': 'Abuso de Álcool (ou Alcoolismo), Ausente'},
  'intervencao': {'codigo': '10031036', 'termo': 'Aconselhar sobre Uso de Álcool'},
  'prioridade': 'Alta',
  'fundamentacao': 'O uso de álcool na gestação representa risco para o desenvolvimento fetal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Avaliar contexto social e familiar relacionado ao uso.'],
                    'repadronizacao': ['Encaminhar para rede de apoio quando houver uso persistente.']},
  'referencias': ['Ministério da Saúde.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Comportamento de saúde prejudicado',
                                  'resultado': 'Comportamento de saúde melhorado',
                                  'intervencao': 'Orientar interrupção do uso de álcool'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Uso de drogas',
  'diagnostico': {'codigo': '10022425', 'termo': 'Abuso de Drogas'},
  'resultado': {'codigo': '10028868', 'termo': 'Abuso de Drogas, Ausente'},
  'intervencao': {'codigo': '10031043', 'termo': 'Aconselhar sobre Abuso de Drogas'},
  'prioridade': 'Alta',
  'fundamentacao': 'Uso de substâncias psicoativas na gestação exige cuidado multiprofissional e redução de danos.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Realizar escuta qualificada sem julgamento.'],
                    'repadronizacao': ['Articular rede de saúde mental, assistência social e pré-natal de alto '
                                       'risco.']},
  'referencias': ['Ministério da Saúde.', 'Rede de Atenção Psicossocial.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Comportamento de saúde prejudicado',
                                  'resultado': 'Comportamento de saúde melhorado',
                                  'intervencao': 'Encaminhar para cuidado compartilhado em saúde mental'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Idade materna menor que 15 anos',
  'diagnostico': {'codigo': '10023225', 'termo': 'Risco de Complicações durante a Gestação (Gravidez)'},
  'resultado': {'codigo': '10042446', 'termo': 'Complicação durante a Gestação (Gravidez), Ausente'},
  'intervencao': {'codigo': '10032567', 'termo': 'Encaminhar a Prestador (ou Provedor) de Cuidados de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Gestação em adolescente muito jovem requer avaliação ampliada de risco clínico, social e familiar.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Avaliar apoio familiar, vínculo escolar e proteção social.'],
                    'repadronizacao': ['Acionar rede de proteção quando necessário.']},
  'referencias': ['Ministério da Saúde.', 'ECA.', 'COFEN 736/2024.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco materno-fetal aumentado',
                                  'resultado': 'Risco materno-fetal reduzido',
                                  'intervencao': 'Encaminhar para acompanhamento de pré-natal de alto risco'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Idade materna maior ou igual a 35 anos',
  'diagnostico': {'codigo': '10023225', 'termo': 'Risco de Complicações durante a Gestação (Gravidez)'},
  'resultado': {'codigo': '10042446', 'termo': 'Complicação durante a Gestação (Gravidez), Ausente'},
  'intervencao': {'codigo': '10041713', 'termo': 'Obter Dados sobre Risco de Doença'},
  'prioridade': 'Média',
  'fundamentacao': 'Idade materna avançada pode estar associada a maior risco obstétrico e comorbidades.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar história reprodutiva, rede de apoio e expectativas familiares.'],
                    'repadronizacao': ['Intensificar acompanhamento se houver comorbidades.']},
  'referencias': ['Ministério da Saúde.', 'Manual de Gestação de Alto Risco.', 'Leininger.'],
  'formulacao_clinica_original': {'diagnostico': 'Risco materno-fetal aumentado',
                                  'resultado': 'Risco materno-fetal reduzido',
                                  'intervencao': 'Avaliar fatores de risco gestacional'},
  'mapeamento_cipe': 'CIPE 2019 — termo oficial vinculado por revisão clínica'}]
