# SAPE IA 2.0 — Regras clínicas de pré-natal
# Recuperadas e normalizadas a partir do acervo do projeto.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Pré-eclâmpsia',
  'diagnostico': {'codigo': '10032017', 'termo': 'Pressão Arterial, Alterada'},
  'resultado': {'codigo': '10027647', 'termo': 'Pressão Arterial, nos Limites Normais'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'A pré-eclâmpsia é síndrome hipertensiva multissistêmica após 20 semanas de gestação, associada a '
                   'proteinúria ou sinais de disfunção orgânica, com risco materno-fetal elevado.',
  'transcultural': {'preservacao': ['Acolher a compreensão cultural da gestante sobre pressão alta e gravidez.'],
                    'acomodacao': ['Explicar sinais de alerta em linguagem simples, incluindo cefaleia, escotomas, dor '
                                   'epigástrica e edema súbito.'],
                    'repadronizacao': ['Reforçar que sintomas graves não devem ser tratados apenas com chás, repouso '
                                       'ou medidas caseiras.']},
  'referencias': ['Ministério da Saúde. Manual de Gestação de Alto Risco.',
                  'FEBRASGO. Síndromes hipertensivas na gestação.',
                  'OMS. Recomendações de cuidado pré-natal.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Eclâmpsia',
  'diagnostico': {'codigo': '10032017', 'termo': 'Pressão Arterial, Alterada'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Eclâmpsia corresponde à ocorrência de convulsões em gestante com síndrome hipertensiva, '
                   'configurando emergência obstétrica com risco de morte materna e fetal.',
  'transcultural': {'preservacao': ['Acolher crenças familiares sobre convulsões sem julgamento.'],
                    'acomodacao': ['Orientar a família sobre necessidade de atendimento de urgência imediato.'],
                    'repadronizacao': ['Desencorajar práticas que atrasem o encaminhamento, como contenção inadequada '
                                       'ou terapias caseiras.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Síndrome HELLP',
  'diagnostico': {'codigo': '10012606', 'termo': 'Processo do Sistema Circulatório, Prejudicado'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'A síndrome HELLP é complicação grave da pré-eclâmpsia, caracterizada por hemólise, elevação de '
                   'enzimas hepáticas e plaquetopenia, exigindo atendimento obstétrico urgente.',
  'transcultural': {'preservacao': ['Acolher sintomas referidos pela gestante, como dor epigástrica e mal-estar.'],
                    'acomodacao': ['Orientar que dor forte no estômago, náuseas intensas ou sangramentos podem indicar '
                                   'gravidade.'],
                    'repadronizacao': ['Evitar banalização de dor epigástrica como azia comum da gravidez.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Hipertensão gestacional grave',
  'diagnostico': {'codigo': '10032017', 'termo': 'Pressão Arterial, Alterada'},
  'resultado': {'codigo': '10027647', 'termo': 'Pressão Arterial, nos Limites Normais'},
  'intervencao': {'codigo': '10044148', 'termo': 'Orientar sobre Medição de Pressão Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Hipertensão gestacional grave aumenta risco de pré-eclâmpsia, eclâmpsia, AVC, descolamento '
                   'placentário, restrição de crescimento fetal e prematuridade.',
  'transcultural': {'preservacao': ['Valorizar cuidados familiares de proteção à gestante.'],
                    'acomodacao': ['Orientar aferição regular da pressão arterial e retorno imediato em sinais de '
                                   'alerta.'],
                    'repadronizacao': ['Desestimular abandono do tratamento anti-hipertensivo por medo de prejudicar o '
                                       'bebê.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Crise hipertensiva',
  'diagnostico': {'codigo': '10032017', 'termo': 'Pressão Arterial, Alterada'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Crise hipertensiva na gestação é emergência clínica e obstétrica, especialmente quando associada a '
                   'sintomas neurológicos, dor epigástrica, dispneia ou alterações fetais.',
  'transcultural': {'preservacao': ['Acolher preocupações da família sobre internação e medicação.'],
                    'acomodacao': ['Explicar risco de complicações maternas e fetais de forma objetiva.'],
                    'repadronizacao': ['Reforçar que pressão muito elevada exige atendimento imediato.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'ITU',
  'diagnostico': {'codigo': '10029915', 'termo': 'Infecção do Trato Urinário'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Alta',
  'fundamentacao': 'Infecção do trato urinário na gestação aumenta risco de pielonefrite, trabalho de parto prematuro '
                   'e baixo peso ao nascer, exigindo tratamento adequado e controle.',
  'transcultural': {'preservacao': ['Reconhecer práticas seguras de higiene íntima já utilizadas.'],
                    'acomodacao': ['Orientar hidratação, coleta adequada de urina e adesão ao antibiótico prescrito.'],
                    'repadronizacao': ['Evitar automedicação e interrupção do tratamento após melhora dos sintomas.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Pielonefrite',
  'diagnostico': {'codigo': '10029915', 'termo': 'Infecção do Trato Urinário'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Pielonefrite na gestação é infecção urinária alta, geralmente com febre, dor lombar e '
                   'comprometimento sistêmico, podendo causar sepse, prematuridade e complicações maternas.',
  'transcultural': {'preservacao': ['Acolher relatos de dor lombar e febre conforme linguagem local.'],
                    'acomodacao': ['Orientar urgência de atendimento, mesmo que a gestante já use medidas caseiras.'],
                    'repadronizacao': ['Reforçar que febre com dor lombar na gestação não deve ser tratada apenas em '
                                       'casa.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Bacteriúria assintomática',
  'diagnostico': {'codigo': '10051950', 'termo': 'Risco de Infecção Urinária'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10038112', 'termo': 'Orientar sobre Prevenção de Infecção Cruzada'},
  'prioridade': 'Alta',
  'fundamentacao': 'Bacteriúria assintomática na gestação deve ser tratada conforme protocolo, pois pode evoluir para '
                   'pielonefrite e aumentar risco de complicações obstétricas.',
  'transcultural': {'preservacao': ['Acolher a percepção de ausência de doença por não haver sintomas.'],
                    'acomodacao': ['Explicar que infecção pode existir mesmo sem dor ou ardência.'],
                    'repadronizacao': ['Reforçar necessidade de tratamento completo e controle laboratorial.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Candidíase',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Média',
  'fundamentacao': 'Candidíase vulvovaginal é frequente na gestação e pode causar corrimento, prurido e desconforto, '
                   'exigindo diagnóstico clínico e tratamento seguro para gestantes.',
  'transcultural': {'preservacao': ['Acolher pudor e crenças sobre sintomas íntimos.'],
                    'acomodacao': ['Garantir privacidade e orientar higiene íntima adequada.'],
                    'repadronizacao': ['Desencorajar duchas vaginais, pomadas sem prescrição e receitas caseiras '
                                       'intravaginais.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Vaginose bacteriana',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Média',
  'fundamentacao': 'Vaginose bacteriana pode cursar com corrimento e odor vaginal, sendo associada a maior risco de '
                   'complicações obstétricas quando sintomática.',
  'transcultural': {'preservacao': ['Respeitar formas culturais de cuidado íntimo que não causem dano.'],
                    'acomodacao': ['Orientar tratamento prescrito e evitar produtos irritantes.'],
                    'repadronizacao': ['Reorientar a crença de que odor vaginal deve ser tratado com duchas ou '
                                       'substâncias caseiras.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Tricomoníase',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Média',
  'fundamentacao': 'Tricomoníase é infecção sexualmente transmissível que pode causar corrimento, prurido e '
                   'desconforto, exigindo tratamento da gestante e avaliação da parceria sexual.',
  'transcultural': {'preservacao': ['Acolher a gestante sem julgamento moral.'],
                    'acomodacao': ['Orientar prevenção de reinfecção e necessidade de abordagem da parceria.'],
                    'repadronizacao': ['Reduzir estigma e reforçar tratamento adequado como proteção materno-fetal.']},
  'referencias': ['Ministério da Saúde. PCDT IST.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Sangramento vaginal no primeiro trimestre',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10028120', 'termo': 'Sangramento, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sangramento no primeiro trimestre pode estar associado a ameaça de abortamento, abortamento em '
                   'curso, gravidez ectópica ou doença trofoblástica, necessitando avaliação imediata.',
  'transcultural': {'preservacao': ['Acolher medos e crenças familiares sobre perda gestacional.'],
                    'acomodacao': ['Orientar sinais de gravidade e necessidade de avaliação mesmo com pequeno volume.'],
                    'repadronizacao': ['Evitar culpabilização da gestante e atraso na busca por cuidado.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Sangramento vaginal no segundo trimestre',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10028120', 'termo': 'Sangramento, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sangramento no segundo trimestre pode indicar condições obstétricas relevantes, como alterações '
                   'placentárias, abortamento tardio, insuficiência cervical ou trabalho de parto prematuro.',
  'transcultural': {'preservacao': ['Acolher a descrição da gestante sobre cor, volume e dor.'],
                    'acomodacao': ['Explicar que todo sangramento na gestação exige avaliação.'],
                    'repadronizacao': ['Evitar observação domiciliar prolongada sem avaliação profissional.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Sangramento vaginal no terceiro trimestre',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sangramento no terceiro trimestre pode estar associado a placenta prévia, descolamento prematuro '
                   'de placenta ou início de trabalho de parto, exigindo avaliação obstétrica urgente.',
  'transcultural': {'preservacao': ['Acolher práticas familiares de apoio durante urgências.'],
                    'acomodacao': ['Orientar deslocamento imediato e evitar toque vaginal fora de ambiente adequado.'],
                    'repadronizacao': ['Reforçar que sangramento no fim da gestação pode ser emergência.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Ameaça de abortamento',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Ameaça de abortamento é caracterizada por sangramento vaginal no início da gestação com colo '
                   'geralmente fechado, exigindo avaliação clínica e ultrassonográfica quando indicada.',
  'transcultural': {'preservacao': ['Acolher sofrimento emocional e crenças sobre perda gestacional.'],
                    'acomodacao': ['Orientar repouso relativo conforme avaliação e retorno se piora.'],
                    'repadronizacao': ['Evitar culpa, automedicação e práticas invasivas caseiras.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Abortamento',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10028379', 'termo': 'Processo do Sistema Circulatório, Positivo'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Abortamento pode apresentar sangramento, dor abdominal, eliminação de tecidos e risco de '
                   'hemorragia, infecção e sofrimento psíquico, requerendo assistência imediata e humanizada.',
  'transcultural': {'preservacao': ['Respeitar luto, crenças espirituais e rituais familiares seguros.'],
                    'acomodacao': ['Oferecer acolhimento, privacidade e orientação sobre sinais de gravidade.'],
                    'repadronizacao': ['Combater julgamento, culpa e abandono do cuidado pós-evento.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Placenta prévia',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Placenta prévia pode causar sangramento vaginal indolor no segundo ou terceiro trimestre e está '
                   'associada a risco hemorrágico materno-fetal, exigindo acompanhamento especializado.',
  'transcultural': {'preservacao': ['Acolher medo da gestante diante do sangramento.'],
                    'acomodacao': ['Orientar repouso, sinais de alerta e comparecimento imediato se sangrar.'],
                    'repadronizacao': ['Evitar toque vaginal e práticas caseiras diante de sangramento.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Descolamento prematuro de placenta',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Descolamento prematuro de placenta é emergência obstétrica, podendo causar dor abdominal intensa, '
                   'hipertonia uterina, sangramento e sofrimento fetal.',
  'transcultural': {'preservacao': ['Acolher a percepção materna de dor intensa ou mudança súbita.'],
                    'acomodacao': ['Orientar que dor forte com sangramento ou mal-estar exige urgência.'],
                    'repadronizacao': ['Evitar espera domiciliar por melhora espontânea.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Rotura prematura de membranas',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Rotura prematura de membranas aumenta risco de infecção, prematuridade e sofrimento fetal, '
                   'exigindo avaliação obstétrica imediata e conduta conforme idade gestacional.',
  'transcultural': {'preservacao': ['Valorizar o relato da gestante sobre perda de líquido.'],
                    'acomodacao': ['Orientar observar cor, odor e quantidade, sem retardar atendimento.'],
                    'repadronizacao': ['Evitar banho de imersão, relação sexual ou toque vaginal após perda de '
                                       'líquido.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Trabalho de parto prematuro',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Trabalho de parto antes de 37 semanas está associado a morbimortalidade neonatal, exigindo '
                   'reconhecimento precoce de contrações regulares, dor lombar, pressão pélvica, sangramento ou perda '
                   'de líquido.',
  'transcultural': {'preservacao': ['Valorizar a percepção da gestante sobre sinais corporais.'],
                    'acomodacao': ['Construir plano de deslocamento rápido, considerando território e transporte.'],
                    'repadronizacao': ['Reforçar que contrações antes do termo não devem ser aguardadas em casa.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Contrações uterinas prematuras',
  'diagnostico': {'codigo': '10006364', 'termo': 'Contração Uterina'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Contrações uterinas prematuras podem indicar ameaça de trabalho de parto prematuro, especialmente '
                   'quando regulares, dolorosas ou associadas a perda de líquido e sangramento.',
  'transcultural': {'preservacao': ['Acolher a forma como a gestante descreve cólicas e endurecimento uterino.'],
                    'acomodacao': ['Orientar registro de frequência e duração das contrações.'],
                    'repadronizacao': ['Evitar normalizar contrações regulares antes de 37 semanas.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Restrição de crescimento fetal',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Restrição de crescimento fetal indica risco de insuficiência placentária, hipóxia, morbidade '
                   'neonatal e óbito fetal, exigindo investigação, vigilância fetal e acompanhamento especializado.',
  'transcultural': {'preservacao': ['Valorizar práticas familiares de cuidado nutricional e repouso seguro.'],
                    'acomodacao': ['Orientar importância do acompanhamento e dos exames seriados.'],
                    'repadronizacao': ['Evitar atribuir baixo crescimento fetal apenas a característica familiar sem '
                                       'avaliação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Oligodrâmnio',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Oligodrâmnio pode estar relacionado a rotura de membranas, insuficiência placentária, restrição de '
                   'crescimento fetal ou malformações, exigindo avaliação obstétrica e vigilância fetal.',
  'transcultural': {'preservacao': ['Acolher preocupações familiares sobre o líquido amniótico.'],
                    'acomodacao': ['Orientar sinais de alerta, como perda de líquido e redução dos movimentos fetais.'],
                    'repadronizacao': ['Evitar interpretação de que hidratação isolada resolve todos os casos sem '
                                       'avaliação médica.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Polidrâmnio',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Polidrâmnio pode estar associado a diabetes gestacional, alterações fetais, infecções ou outras '
                   'condições, aumentando risco de parto prematuro e complicações obstétricas.',
  'transcultural': {'preservacao': ['Acolher explicações culturais sobre aumento exagerado da barriga.'],
                    'acomodacao': ['Orientar necessidade de investigação e controle glicêmico quando indicado.'],
                    'repadronizacao': ['Evitar normalizar crescimento uterino excessivo sem avaliação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Sofrimento fetal suspeito',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sofrimento fetal suspeito pode ser indicado por alteração de batimentos cardíacos fetais, redução '
                   'de movimentos fetais ou condições maternas graves, exigindo avaliação obstétrica imediata.',
  'transcultural': {'preservacao': ['Valorizar a percepção materna sobre o comportamento fetal.'],
                    'acomodacao': ['Orientar sinais que exigem procura imediata do serviço.'],
                    'repadronizacao': ['Evitar aguardar retorno programado quando há suspeita de alteração fetal.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Redução dos movimentos fetais',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Redução dos movimentos fetais pode indicar comprometimento fetal e deve ser valorizada, '
                   'especialmente após a gestante reconhecer o padrão habitual de movimentação.',
  'transcultural': {'preservacao': ['Valorizar o conhecimento materno sobre o padrão do bebê.'],
                    'acomodacao': ['Orientar busca imediata se houver redução importante ou ausência de movimentos.'],
                    'repadronizacao': ['Desestimular esperar dias para avaliação por acreditar que o bebê está apenas '
                                       'dormindo.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Hiperêmese gravídica',
  'diagnostico': {'codigo': '10020864', 'termo': 'Vômito'},
  'resultado': {'codigo': '10027617', 'termo': 'Equilíbrio Hídrico, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Hiperêmese gravídica envolve vômitos intensos, perda ponderal, desidratação e possível distúrbio '
                   'eletrolítico, podendo exigir hidratação venosa e suporte clínico.',
  'transcultural': {'preservacao': ['Acolher práticas alimentares seguras que melhorem náuseas.'],
                    'acomodacao': ['Orientar sinais de desidratação e necessidade de atendimento.'],
                    'repadronizacao': ['Evitar automedicação e uso de ervas sem segurança na gestação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Desidratação',
  'diagnostico': {'codigo': '10041895', 'termo': 'Desidratação'},
  'resultado': {'codigo': '10027617', 'termo': 'Equilíbrio Hídrico, Eficaz'},
  'intervencao': {'codigo': '10036112', 'termo': 'Orientar sobre Hidratação'},
  'prioridade': 'Alta',
  'fundamentacao': 'Desidratação na gestação pode decorrer de vômitos, diarreia, febre ou baixa ingestão hídrica, '
                   'aumentando risco de hipotensão, contrações e comprometimento materno-fetal.',
  'transcultural': {'preservacao': ['Valorizar bebidas e alimentos locais seguros que favoreçam hidratação.'],
                    'acomodacao': ['Orientar ingestão hídrica fracionada conforme tolerância.'],
                    'repadronizacao': ['Evitar restrição hídrica por medo de urinar com frequência.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Anemia grave',
  'diagnostico': {'codigo': '10012606', 'termo': 'Processo do Sistema Circulatório, Prejudicado'},
  'resultado': {'codigo': '10028379', 'termo': 'Processo do Sistema Circulatório, Positivo'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Alta',
  'fundamentacao': 'Anemia grave na gestação aumenta risco de fadiga intensa, infecção, parto prematuro, baixo peso ao '
                   'nascer, hemorragia e desfechos materno-fetais adversos.',
  'transcultural': {'preservacao': ['Estimular alimentos regionais ricos em ferro e culturalmente aceitos.'],
                    'acomodacao': ['Adequar suplementação e alimentação à rotina e tolerância da gestante.'],
                    'repadronizacao': ['Orientar evitar café ou chá junto das refeições e não suspender ferro sem '
                                       'avaliação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Diabetes gestacional descompensado',
  'diagnostico': {'codigo': '10005876', 'termo': 'Diabetes'},
  'resultado': {'codigo': '10027532', 'termo': 'Processo do Sistema Regulatório, Eficaz'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'Diabetes gestacional descompensado aumenta risco de macrossomia, pré-eclâmpsia, parto traumático, '
                   'hipoglicemia neonatal e complicações metabólicas.',
  'transcultural': {'preservacao': ['Preservar alimentos culturais compatíveis com controle glicêmico.'],
                    'acomodacao': ['Adaptar plano alimentar à renda, acesso e rotina familiar.'],
                    'repadronizacao': ['Reduzir consumo de açúcar, bebidas adoçadas e ultraprocessados.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Febre na gestação',
  'diagnostico': {'codigo': '10007916', 'termo': 'Febre'},
  'resultado': {'codigo': '10033694', 'termo': 'Temperatura Corporal, nos Limites Normais'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Febre na gestação pode indicar infecção urinária, respiratória, intra-amniótica, arbovirose ou '
                   'outras condições com risco materno-fetal, exigindo investigação.',
  'transcultural': {'preservacao': ['Acolher práticas seguras de conforto térmico.'],
                    'acomodacao': ['Orientar hidratação, monitoramento e sinais de gravidade.'],
                    'repadronizacao': ['Evitar automedicação e uso de chás sem segurança gestacional.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Dengue na gestação',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Dengue na gestação aumenta risco de desidratação, sangramentos, plaquetopenia, parto prematuro e '
                   'complicações maternas, exigindo acompanhamento clínico rigoroso.',
  'transcultural': {'preservacao': ['Valorizar medidas comunitárias de eliminação de criadouros.'],
                    'acomodacao': ['Orientar hidratação, sinais de alarme e proteção contra mosquitos.'],
                    'repadronizacao': ['Evitar anti-inflamatórios e automedicação, especialmente diante de suspeita de '
                                       'dengue.']},
  'referencias': ['Ministério da Saúde. Arboviroses na gestação.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Zika na gestação',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Infecção por Zika na gestação está associada a risco de síndrome congênita, alterações '
                   'neurológicas fetais e necessidade de vigilância ultrassonográfica e acompanhamento especializado.',
  'transcultural': {'preservacao': ['Valorizar estratégias comunitárias de prevenção ao mosquito.'],
                    'acomodacao': ['Orientar uso de repelente seguro, barreiras físicas e acompanhamento fetal.'],
                    'repadronizacao': ['Evitar minimizar exantema, febre baixa ou conjuntivite em área de '
                                       'transmissão.']},
  'referencias': ['Ministério da Saúde. Zika e gestação.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'Chikungunya na gestação',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Chikungunya na gestação pode causar febre, artralgia intensa e risco de transmissão perinatal '
                   'quando ocorre próximo ao parto, exigindo vigilância clínica e obstétrica.',
  'transcultural': {'preservacao': ['Valorizar medidas locais de proteção contra mosquitos.'],
                    'acomodacao': ['Orientar repouso, hidratação e sinais de gravidade.'],
                    'repadronizacao': ['Evitar automedicação com anti-inflamatórios sem avaliação profissional.']},
  'referencias': ['Ministério da Saúde. Arboviroses.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Intercorrências obstétricas',
  'achado_clinico': 'COVID-19 na gestação',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'COVID-19 na gestação pode aumentar risco de complicações respiratórias, internação, prematuridade '
                   'e agravamento em gestantes com comorbidades, exigindo avaliação de gravidade, isolamento orientado '
                   'e acompanhamento.',
  'transcultural': {'preservacao': ['Acolher crenças familiares sobre infecções respiratórias sem julgamento.'],
                    'acomodacao': ['Orientar sinais de alerta respiratório, vacinação e medidas preventivas.'],
                    'repadronizacao': ['Combater desinformação sobre COVID-19, vacinação e segurança materno-fetal.']},
  'referencias': ['Ministério da Saúde. COVID-19 e gestação.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']}]
