# SAPE IA 2.0 — Regras clínicas de pré-natal
# Recuperadas e normalizadas a partir do acervo do projeto.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Ácido fólico não iniciado',
  'diagnostico': {'codigo': '10024625', 'termo': 'Regime Terapêutico, Prejudicado'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'O ácido fólico é recomendado no período periconcepcional e no início da gestação para reduzir o '
                   'risco de defeitos do tubo neural. Quando não iniciado, a enfermagem deve orientar início conforme '
                   'protocolo, verificar acesso ao suplemento, registrar conduta e reforçar adesão.',
  'transcultural': {'preservacao': ['Valorizar práticas alimentares seguras e alimentos regionais ricos em folato.'],
                    'acomodacao': ['Adequar a orientação ao acesso da gestante à farmácia da unidade e à rotina '
                                   'diária.'],
                    'repadronizacao': ['Reorientar a ideia de que suplemento só é necessário quando há sintomas.']},
  'referencias': ['Ministério da Saúde. Atenção ao pré-natal de baixo risco.',
                  'FEBRASGO. Assistência pré-natal.',
                  'OMS. Recomendações sobre cuidado pré-natal.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Ácido fólico iniciado tardiamente',
  'diagnostico': {'codigo': '10024625', 'termo': 'Regime Terapêutico, Prejudicado'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Média',
  'fundamentacao': 'O início tardio do ácido fólico reduz o benefício máximo esperado na prevenção de defeitos do tubo '
                   'neural, especialmente quando iniciado após o período de fechamento do tubo neural. Ainda assim, '
                   'deve-se orientar continuidade conforme protocolo e reforçar suplementação adequada.',
  'transcultural': {'preservacao': ['Acolher a história da gestante sem culpabilização.'],
                    'acomodacao': ['Explicar a finalidade do suplemento em linguagem simples.'],
                    'repadronizacao': ['Estimular início precoce em futuras gestações e planejamento reprodutivo.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Baixa adesão ao ácido fólico',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Média',
  'fundamentacao': 'A baixa adesão ao ácido fólico compromete a efetividade da suplementação. A equipe deve investigar '
                   'esquecimento, efeitos adversos, acesso, compreensão da prescrição e crenças sobre medicamentos na '
                   'gestação.',
  'transcultural': {'preservacao': ['Respeitar valores da gestante sobre uso de medicamentos.'],
                    'acomodacao': ['Pactuar horário de uso associado a rotina já existente.'],
                    'repadronizacao': ['Reformular crenças de que vitaminas fazem mal ao bebê.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Sulfato ferroso não iniciado',
  'diagnostico': {'codigo': '10023009', 'termo': 'Ingestão Nutricional, Prejudicada'},
  'resultado': {'codigo': '10037572', 'termo': 'Ingestão Nutricional, nos Limites Normais'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'A suplementação de ferro no pré-natal é recomendada para prevenção e tratamento da anemia '
                   'ferropriva, condição associada a fadiga, infecção, prematuridade e baixo peso ao nascer. Deve-se '
                   'orientar início conforme protocolo e avaliar hemoglobina, ferritina e tolerância.',
  'transcultural': {'preservacao': ['Valorizar alimentos locais ricos em ferro.'],
                    'acomodacao': ['Adequar horário de uso para reduzir desconfortos gastrointestinais.'],
                    'repadronizacao': ['Orientar evitar café, chá preto ou leite junto ao ferro, pois podem reduzir '
                                       'absorção.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Baixa adesão ao sulfato ferroso',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'A baixa adesão ao sulfato ferroso mantém risco de anemia gestacional e suas complicações. A '
                   'enfermagem deve investigar eventos adversos, esquecimento, acesso ao medicamento e orientar '
                   'estratégias para melhorar a tolerância e continuidade.',
  'transcultural': {'preservacao': ['Acolher relatos sobre intolerância e experiências anteriores.'],
                    'acomodacao': ['Negociar horário de uso e estratégias alimentares possíveis.'],
                    'repadronizacao': ['Reforçar que escurecimento das fezes é esperado e não deve motivar suspensão '
                                       'isolada.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Náuseas associadas ao sulfato ferroso',
  'diagnostico': {'codigo': '10012453', 'termo': 'Náusea'},
  'resultado': {'codigo': '10028992', 'termo': 'Náusea, Ausente'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Média',
  'fundamentacao': 'Náuseas podem ocorrer com uso de sulfato ferroso e reduzir adesão. Deve-se orientar forma correta '
                   'de uso, avaliar possibilidade de tomada após alimento leve quando necessário, verificar gravidade '
                   'e encaminhar para ajuste terapêutico se intolerância persistente.',
  'transcultural': {'preservacao': ['Valorizar alimentos culturalmente aceitos que reduzam enjoo.'],
                    'acomodacao': ['Ajustar horário de uso conforme maior tolerância da gestante.'],
                    'repadronizacao': ['Evitar suspensão sem comunicação à equipe de saúde.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Constipação associada ao sulfato ferroso',
  'diagnostico': {'codigo': '10004999', 'termo': 'Constipação'},
  'resultado': {'codigo': '10027800', 'termo': 'Eliminação Intestinal, Eficaz'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Média',
  'fundamentacao': 'O sulfato ferroso pode agravar constipação, sintoma já comum na gestação. A enfermagem deve '
                   'orientar ingestão hídrica, fibras, atividade física segura e comunicar a equipe caso o efeito '
                   'adverso comprometa a adesão.',
  'transcultural': {'preservacao': ['Estimular alimentos regionais ricos em fibras.'],
                    'acomodacao': ['Adequar hidratação à realidade de acesso à água segura.'],
                    'repadronizacao': ['Evitar laxantes, chás purgativos ou automedicação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Cálcio indicado',
  'diagnostico': {'codigo': '10023009', 'termo': 'Ingestão Nutricional, Prejudicada'},
  'resultado': {'codigo': '10037572', 'termo': 'Ingestão Nutricional, nos Limites Normais'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Média',
  'fundamentacao': 'A suplementação de cálcio pode ser indicada em gestantes com baixa ingestão dietética ou maior '
                   'risco de pré-eclâmpsia, conforme avaliação clínica e protocolo. Deve-se orientar uso correto, '
                   'intervalo em relação ao ferro e acompanhamento.',
  'transcultural': {'preservacao': ['Valorizar fontes alimentares culturais de cálcio.'],
                    'acomodacao': ['Adequar suplementação ao horário possível e à rotina alimentar.'],
                    'repadronizacao': ['Orientar não tomar cálcio junto ao ferro para não prejudicar absorção.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Baixa adesão ao cálcio',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Média',
  'fundamentacao': 'A baixa adesão ao cálcio reduz o potencial benefício preventivo em gestantes com indicação. A '
                   'enfermagem deve identificar esquecimento, efeitos gastrointestinais, dificuldade de acesso e '
                   'orientar horários separados do sulfato ferroso.',
  'transcultural': {'preservacao': ['Considerar hábitos alimentares e crenças sobre leite e derivados.'],
                    'acomodacao': ['Pactuar horários simples para evitar esquecimento.'],
                    'repadronizacao': ['Reforçar finalidade preventiva da suplementação quando indicada.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Uso inadequado de medicamentos na gestação',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'O uso inadequado de medicamentos na gestação pode expor mãe e feto a riscos evitáveis, incluindo '
                   'toxicidade, efeitos teratogênicos, interações e falha terapêutica. Deve-se revisar todos os '
                   'medicamentos em uso e encaminhar para avaliação quando houver risco.',
  'transcultural': {'preservacao': ['Acolher práticas familiares de cuidado sem julgamento.'],
                    'acomodacao': ['Solicitar que a gestante leve medicamentos, receitas e produtos usados às '
                                   'consultas.'],
                    'repadronizacao': ['Reforçar que todo medicamento na gestação deve ser avaliado por profissional '
                                       'de saúde.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Automedicação',
  'diagnostico': {'codigo': '10025806', 'termo': 'Comportamento de Saúde, Prejudicado'},
  'resultado': {'codigo': '10028276', 'termo': 'Comportamento de Saúde, Positivo'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'A automedicação na gestação pode causar eventos adversos maternos e fetais, mascarar sinais de '
                   'gravidade e retardar diagnóstico. A enfermagem deve investigar substâncias utilizadas, orientar '
                   'riscos e fortalecer acesso à avaliação profissional.',
  'transcultural': {'preservacao': ['Reconhecer o papel da família na tomada de decisão sobre cuidados.'],
                    'acomodacao': ['Orientar alternativas seguras de procura do serviço de saúde.'],
                    'repadronizacao': ['Modificar a prática de usar medicamentos por indicação de terceiros.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Uso de anti-inflamatório sem orientação',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10028120', 'termo': 'Risco, Reduzido'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'Anti-inflamatórios não esteroidais podem apresentar riscos na gestação, especialmente em fases '
                   'específicas, incluindo alterações fetais, renais, ducto arterioso e complicações maternas. O uso '
                   'sem orientação deve ser interrompido e avaliado por profissional habilitado.',
  'transcultural': {'preservacao': ['Acolher a motivação da gestante para alívio da dor.'],
                    'acomodacao': ['Orientar busca de alternativas seguras prescritas pela equipe.'],
                    'repadronizacao': ['Evitar uso de anti-inflamatórios por conta própria durante a gestação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Uso de fitoterápico sem avaliação',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10028120', 'termo': 'Risco, Reduzido'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Média',
  'fundamentacao': 'Fitoterápicos podem conter substâncias com efeitos uterotônicos, hepatotóxicos, nefrotóxicos, '
                   'anticoagulantes ou interações medicamentosas. Na gestação, seu uso deve ser avaliado quanto à '
                   'segurança, dose, procedência e indicação.',
  'transcultural': {'preservacao': ['Respeitar o uso tradicional de plantas como parte da cultura familiar.'],
                    'acomodacao': ['Dialogar sobre quais produtos são usados, finalidade e frequência.'],
                    'repadronizacao': ['Substituir práticas de risco por alternativas seguras pactuadas com a '
                                       'equipe.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Uso de plantas medicinais com risco gestacional',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10028120', 'termo': 'Risco, Reduzido'},
  'intervencao': {'codigo': '10019502', 'termo': 'Orientar sobre Segurança'},
  'prioridade': 'Alta',
  'fundamentacao': 'Algumas plantas medicinais podem provocar contrações uterinas, sangramento, toxicidade, alterações '
                   'hepáticas ou interação com medicamentos. A enfermagem deve identificar uso, orientar riscos e '
                   'comunicar a equipe para avaliação segura.',
  'transcultural': {'preservacao': ['Valorizar saberes tradicionais que não coloquem a gestação em risco.'],
                    'acomodacao': ['Negociar suspensão ou substituição de plantas potencialmente perigosas.'],
                    'repadronizacao': ['Reorientar a crença de que todo produto natural é seguro na gravidez.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Anti-hipertensivo prescrito',
  'diagnostico': {'codigo': '10009394', 'termo': 'Hipertensão'},
  'resultado': {'codigo': '10027647', 'termo': 'Pressão Arterial, nos Limites Normais'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'O uso de anti-hipertensivo na gestação pode ser necessário para controle pressórico e prevenção de '
                   'complicações como pré-eclâmpsia grave, AVC, restrição de crescimento fetal e desfechos maternos '
                   'adversos. A enfermagem deve orientar uso correto, monitoramento da pressão e sinais de alerta.',
  'transcultural': {'preservacao': ['Acolher práticas seguras de autocuidado e apoio familiar.'],
                    'acomodacao': ['Pactuar horários de uso conforme rotina da gestante.'],
                    'repadronizacao': ['Reforçar que pressão controlada não significa suspender medicamento sem '
                                       'orientação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Baixa adesão ao anti-hipertensivo',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'A baixa adesão ao anti-hipertensivo aumenta risco de crise hipertensiva, pré-eclâmpsia grave, '
                   'eclâmpsia, descolamento placentário e complicações fetais. É necessário investigar barreiras, '
                   'orientar sinais de alerta e reforçar acompanhamento.',
  'transcultural': {'preservacao': ['Reconhecer crenças familiares sobre pressão alta.'],
                    'acomodacao': ['Usar lembretes e rotina diária para melhorar adesão.'],
                    'repadronizacao': ['Desestimular suspensão por melhora dos sintomas ou ausência de sintomas.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Efeitos adversos do anti-hipertensivo',
  'diagnostico': {'codigo': '10033557', 'termo': 'Efeito Secundário da Medicação'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'Efeitos adversos podem comprometer adesão ao anti-hipertensivo e exigem avaliação clínica para '
                   'ajuste seguro. Sintomas como tontura intensa, síncope, dispneia, edema importante ou piora clínica '
                   'devem ser comunicados imediatamente.',
  'transcultural': {'preservacao': ['Acolher relatos da gestante sobre sensações após o medicamento.'],
                    'acomodacao': ['Orientar registro de sintomas, horários e pressão arterial quando possível.'],
                    'repadronizacao': ['Evitar interrupção espontânea do tratamento por efeitos adversos sem '
                                       'avaliação.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Insulina prescrita',
  'diagnostico': {'codigo': '10005876', 'termo': 'Diabetes'},
  'resultado': {'codigo': '10027532', 'termo': 'Processo do Sistema Regulatório, Eficaz'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'A insulina pode ser indicada no diabetes gestacional ou diabetes prévio quando medidas alimentares '
                   'e atividade física não são suficientes ou conforme avaliação clínica. O uso correto reduz '
                   'hiperglicemia materna e complicações fetais.',
  'transcultural': {'preservacao': ['Valorizar o cuidado familiar no apoio ao tratamento.'],
                    'acomodacao': ['Ensinar aplicação considerando rotina, escolaridade e acesso a insumos.'],
                    'repadronizacao': ['Reforçar que insulina não representa fracasso da gestante, mas proteção '
                                       'materno-fetal.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Dificuldade no uso de insulina',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019502', 'termo': 'Orientar sobre Segurança'},
  'prioridade': 'Alta',
  'fundamentacao': 'Dificuldade no preparo, dose, aplicação, rodízio de locais ou descarte de materiais pode gerar '
                   'hiperglicemia, hipoglicemia ou lesões locais. A enfermagem deve demonstrar a técnica, observar '
                   'retorno demonstrativo e reforçar armazenamento e descarte.',
  'transcultural': {'preservacao': ['Incluir pessoa de confiança quando a gestante desejar.'],
                    'acomodacao': ['Usar demonstração prática e linguagem simples.'],
                    'repadronizacao': ['Corrigir técnicas inseguras de aplicação ou reutilização inadequada de '
                                       'materiais.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Medo de aplicar insulina',
  'diagnostico': {'codigo': '10007738', 'termo': 'Medo'},
  'resultado': {'codigo': '10027858', 'termo': 'Medo, Reduzido'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'O medo da aplicação de insulina pode levar à omissão de doses e descontrole glicêmico. A '
                   'enfermagem deve acolher, demonstrar técnica, permitir treino supervisionado e reforçar benefícios '
                   'para mãe e feto.',
  'transcultural': {'preservacao': ['Acolher experiências familiares com injeções e diabetes.'],
                    'acomodacao': ['Permitir apoio de familiar ou cuidador escolhido pela gestante.'],
                    'repadronizacao': ['Reduzir crenças de que insulina causa dependência ou prejudica o bebê.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Falta de armazenamento adequado da insulina',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10028120', 'termo': 'Risco, Reduzido'},
  'intervencao': {'codigo': '10019502', 'termo': 'Orientar sobre Segurança'},
  'prioridade': 'Alta',
  'fundamentacao': 'Armazenamento inadequado pode comprometer a estabilidade da insulina e prejudicar o controle '
                   'glicêmico. Deve-se orientar conservação conforme apresentação, proteção contra calor e '
                   'congelamento, transporte seguro e descarte de insumos.',
  'transcultural': {'preservacao': ['Reconhecer limitações territoriais, como ausência de energia elétrica contínua.'],
                    'acomodacao': ['Construir estratégia viável de conservação com a família e a rede de saúde.'],
                    'repadronizacao': ['Evitar exposição da insulina ao sol, calor excessivo ou congelamento.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Antibiótico prescrito para ITU',
  'diagnostico': {'codigo': '10029915', 'termo': 'Infecção do Trato Urinário'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'ITU na gestação deve ser tratada adequadamente para prevenir pielonefrite, parto prematuro e baixo '
                   'peso ao nascer. A enfermagem deve orientar uso correto do antibiótico, hidratação, sinais de '
                   'alerta e retorno para controle quando indicado.',
  'transcultural': {'preservacao': ['Valorizar práticas seguras de higiene e hidratação.'],
                    'acomodacao': ['Ajustar orientação ao horário das doses e rotina da gestante.'],
                    'repadronizacao': ['Evitar suspensão do antibiótico após melhora dos sintomas.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Baixa adesão ao antibiótico',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'A baixa adesão ao antibiótico pode resultar em persistência da infecção urinária, pielonefrite, '
                   'resistência bacteriana e complicações obstétricas. Deve-se reforçar conclusão do tratamento e '
                   'reavaliação se sintomas persistirem.',
  'transcultural': {'preservacao': ['Acolher motivos de interrupção do tratamento.'],
                    'acomodacao': ['Criar plano de horários simples para completar o esquema.'],
                    'repadronizacao': ['Reforçar que melhora inicial não significa cura completa.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Tratamento de sífilis indicado',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'A sífilis na gestação requer tratamento oportuno com penicilina benzatina conforme estágio '
                   'clínico, além de seguimento sorológico e abordagem da parceria sexual. O tratamento adequado '
                   'previne sífilis congênita, abortamento, natimortalidade e prematuridade.',
  'transcultural': {'preservacao': ['Garantir acolhimento sem julgamento e preservação do sigilo.'],
                    'acomodacao': ['Orientar a gestante e parceria sobre tratamento e prevenção de reinfecção.'],
                    'repadronizacao': ['Reduzir estigma e reforçar que tratamento completo protege o bebê.']},
  'referencias': ['Ministério da Saúde. PCDT para IST.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Medo da penicilina benzatina',
  'diagnostico': {'codigo': '10007738', 'termo': 'Medo'},
  'resultado': {'codigo': '10027858', 'termo': 'Medo, Reduzido'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'O medo da penicilina benzatina pode atrasar o tratamento da sífilis e aumentar risco de '
                   'transmissão vertical. A enfermagem deve acolher, explicar benefícios, possíveis reações, medidas '
                   'de segurança e fluxo de atendimento para administração.',
  'transcultural': {'preservacao': ['Acolher experiências prévias dolorosas ou relatos familiares.'],
                    'acomodacao': ['Explicar o procedimento e estratégias de conforto.'],
                    'repadronizacao': ['Reforçar que adiar tratamento aumenta risco para o bebê.']},
  'referencias': ['Ministério da Saúde. PCDT para IST.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Tratamento do parceiro não realizado',
  'diagnostico': {'codigo': '10015133', 'termo': 'Risco de Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Alta',
  'fundamentacao': 'A ausência de tratamento da parceria sexual em casos de sífilis ou outras IST aumenta risco de '
                   'reinfecção materna e transmissão vertical. A equipe deve orientar tratamento da parceria, uso de '
                   'preservativo e seguimento conforme protocolo.',
  'transcultural': {'preservacao': ['Respeitar dinâmica familiar e segurança da gestante.'],
                    'acomodacao': ['Ofertar aconselhamento sigiloso e estratégias de convocação da parceria.'],
                    'repadronizacao': ['Reforçar que tratar somente a gestante pode não impedir reinfecção.']},
  'referencias': ['Ministério da Saúde. PCDT para IST.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Antirretroviral indicado',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'A terapia antirretroviral na gestação é fundamental para reduzir carga viral materna e prevenir '
                   'transmissão vertical do HIV. A enfermagem deve orientar adesão diária, manejo de efeitos adversos, '
                   'exames de seguimento e sigilo.',
  'transcultural': {'preservacao': ['Garantir acolhimento, sigilo e respeito à história da gestante.'],
                    'acomodacao': ['Adaptar estratégias de adesão à rotina e rede de apoio.'],
                    'repadronizacao': ['Combater estigma e crenças que levem à interrupção do tratamento.']},
  'referencias': ['Ministério da Saúde. PCDT HIV em gestantes.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Baixa adesão ao antirretroviral',
  'diagnostico': {'codigo': '10022155', 'termo': 'Adesão ao Regime Terapêutico, Prejudicada'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'A baixa adesão ao antirretroviral pode manter carga viral detectável e aumentar risco de '
                   'transmissão vertical do HIV. A equipe deve identificar barreiras, efeitos adversos, estigma, '
                   'acesso ao medicamento e organizar suporte intensivo.',
  'transcultural': {'preservacao': ['Proteger sigilo e autonomia da gestante.'],
                    'acomodacao': ['Planejar horários discretos e compatíveis com sua rotina.'],
                    'repadronizacao': ['Reduzir crenças de abandono terapêutico por medo de descoberta do '
                                       'diagnóstico.']},
  'referencias': ['Ministério da Saúde. PCDT HIV em gestantes.',
                  'FEBRASGO.',
                  'OMS.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Medicamento controlado em uso',
  'diagnostico': {'codigo': '10024625', 'termo': 'Regime Terapêutico, Prejudicado'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019502', 'termo': 'Orientar sobre Segurança'},
  'prioridade': 'Alta',
  'fundamentacao': 'Medicamentos controlados durante a gestação exigem avaliação de risco-benefício, dose, indicação, '
                   'interação medicamentosa, dependência, abstinência e possíveis efeitos fetais. A suspensão abrupta '
                   'também pode ser perigosa, devendo ocorrer apenas com orientação profissional.',
  'transcultural': {'preservacao': ['Acolher a necessidade clínica sem julgamento.'],
                    'acomodacao': ['Orientar acompanhamento compartilhado com pré-natal e saúde mental quando '
                                   'necessário.'],
                    'repadronizacao': ['Evitar suspensão abrupta ou aumento de dose por conta própria.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Uso de psicotrópico na gestação',
  'diagnostico': {'codigo': '10022402', 'termo': 'Processo Psicológico, Prejudicado'},
  'resultado': {'codigo': '10027649', 'termo': 'Processo Psicológico, Eficaz'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Alta',
  'fundamentacao': 'O uso de psicotrópicos na gestação deve ser acompanhado com avaliação de risco-benefício, pois '
                   'tanto a doença mental não tratada quanto o uso inadequado de medicamentos podem trazer riscos. A '
                   'enfermagem deve orientar não interromper abruptamente e articular cuidado multiprofissional.',
  'transcultural': {'preservacao': ['Reduzir estigma e acolher sofrimento psíquico.'],
                    'acomodacao': ['Incluir rede de apoio quando autorizado pela gestante.'],
                    'repadronizacao': ['Reforçar que tratamento em saúde mental também faz parte do cuidado '
                                       'pré-natal.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Medicações e suplementação',
  'achado_clinico': 'Necessidade de conciliação medicamentosa',
  'diagnostico': {'codigo': '10024625', 'termo': 'Regime Terapêutico, Prejudicado'},
  'resultado': {'codigo': '10030185', 'termo': 'Adesão ao Regime Terapêutico'},
  'intervencao': {'codigo': '10019470', 'termo': 'Orientar sobre Medicação'},
  'prioridade': 'Alta',
  'fundamentacao': 'A conciliação medicamentosa no pré-natal identifica medicamentos prescritos, automedicação, '
                   'fitoterápicos, suplementos, duplicidades, interações e riscos gestacionais. É essencial para '
                   'segurança materno-fetal e continuidade do cuidado.',
  'transcultural': {'preservacao': ['Acolher todos os produtos usados pela gestante sem julgamento.'],
                    'acomodacao': ['Solicitar que leve receitas, cartelas, frascos, chás e suplementos às consultas.'],
                    'repadronizacao': ['Organizar lista única e segura de medicamentos autorizados e contraindicações '
                                       'orientadas.']},
  'referencias': ['Ministério da Saúde.', 'FEBRASGO.', 'OMS.', 'COFEN Resolução nº 736/2024.', 'Leininger.']}]
