# SAPE IA 2.0 — Regras clínicas de pré-natal
# Recuperadas e normalizadas a partir do acervo do projeto.

REGRAS = [{'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Náuseas',
  'diagnostico': {'codigo': '10012453', 'termo': 'Náusea'},
  'resultado': {'codigo': '10028992', 'termo': 'Náusea, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Náuseas são frequentes no primeiro trimestre, geralmente relacionadas a alterações hormonais. A '
                   'avaliação deve identificar intensidade, hidratação, perda ponderal e impacto funcional, orientando '
                   'fracionamento alimentar, hidratação e sinais de alerta.',
  'transcultural': {'preservacao': ['Valorizar práticas alimentares culturais seguras que aliviem náuseas.'],
                    'acomodacao': ['Adaptar horários e tipos de alimentos à rotina e tolerância da gestante.'],
                    'repadronizacao': ['Reorientar uso de chás, ervas ou medicamentos sem avaliação profissional.']},
  'referencias': ['Ministério da Saúde. Pré-natal de baixo risco.',
                  'OMS. Recomendações sobre cuidados pré-natais.',
                  'FEBRASGO. Assistência pré-natal.',
                  'COFEN Resolução nº 736/2024.',
                  'Leininger. Teoria Transcultural.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Vômitos',
  'diagnostico': {'codigo': '10020864', 'termo': 'Vômito'},
  'resultado': {'codigo': '10029134', 'termo': 'Vômito, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Média',
  'fundamentacao': 'Vômitos persistentes podem causar desidratação, perda de peso e distúrbios hidroeletrolíticos. No '
                   'pré-natal, deve-se avaliar frequência, aceitação oral, diurese, sinais de desidratação e '
                   'necessidade de encaminhamento.',
  'transcultural': {'preservacao': ['Reconhecer alimentos culturalmente aceitos que melhorem a tolerância oral.'],
                    'acomodacao': ['Orientar pequenas refeições, líquidos em pequenos volumes e repouso após '
                                   'alimentação.'],
                    'repadronizacao': ['Desencorajar automedicação antiemética e práticas inseguras.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Hiperêmese gravídica',
  'diagnostico': {'codigo': '10020864', 'termo': 'Vômito'},
  'resultado': {'codigo': '10027617', 'termo': 'Equilíbrio Hídrico, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Hiperêmese gravídica caracteriza-se por vômitos intensos, perda de peso, desidratação, cetonúria e '
                   'risco de desequilíbrio metabólico. Requer avaliação imediata, hidratação, suporte clínico e '
                   'possível encaminhamento hospitalar.',
  'transcultural': {'preservacao': ['Acolher explicações culturais da gestante sobre o mal-estar.'],
                    'acomodacao': ['Explicar sinais de gravidade de forma simples para gestante e família.'],
                    'repadronizacao': ['Reforçar que vômitos intensos não devem ser tratados apenas com medidas '
                                       'caseiras.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Azia',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Azia é comum na gestação por relaxamento do esfíncter esofágico e compressão uterina. Deve-se '
                   'orientar refeições menores, evitar deitar após comer e observar sinais de alarme, como dor intensa '
                   'ou vômitos persistentes.',
  'transcultural': {'preservacao': ['Manter alimentos tradicionais que não piorem sintomas.'],
                    'acomodacao': ['Ajustar orientação alimentar à rotina familiar.'],
                    'repadronizacao': ['Evitar automedicação com antiácidos ou bicarbonato sem orientação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Pirose',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Pirose gestacional geralmente decorre de refluxo gastroesofágico. A enfermagem deve orientar '
                   'medidas posturais, fracionamento alimentar, redução de alimentos irritantes e avaliação se '
                   'sintomas forem intensos ou persistentes.',
  'transcultural': {'preservacao': ['Preservar preparações alimentares locais bem toleradas.'],
                    'acomodacao': ['Negociar substituições alimentares possíveis.'],
                    'repadronizacao': ['Desestimular condutas caseiras de risco ou uso indiscriminado de '
                                       'medicamentos.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Constipação',
  'diagnostico': {'codigo': '10004999', 'termo': 'Constipação'},
  'resultado': {'codigo': '10027800', 'termo': 'Eliminação Intestinal, Eficaz'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Constipação é frequente na gestação por alterações hormonais, redução da motilidade intestinal e '
                   'suplementação de ferro. Orienta-se aumento de fibras, ingestão hídrica, atividade física se não '
                   'contraindicada e evitar laxantes sem prescrição.',
  'transcultural': {'preservacao': ['Valorizar alimentos regionais ricos em fibras.'],
                    'acomodacao': ['Adequar consumo de água e fibras à disponibilidade local.'],
                    'repadronizacao': ['Evitar uso rotineiro de laxantes, chás purgativos ou automedicação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Diarreia',
  'diagnostico': {'codigo': '10005933', 'termo': 'Diarreia'},
  'resultado': {'codigo': '10027800', 'termo': 'Eliminação Intestinal, Eficaz'},
  'intervencao': {'codigo': '10036112', 'termo': 'Orientar sobre Hidratação'},
  'prioridade': 'Média',
  'fundamentacao': 'Diarreia pode causar desidratação e indicar infecção gastrointestinal. A enfermagem deve avaliar '
                   'duração, febre, sangue nas fezes, sinais de desidratação, orientar hidratação e encaminhar quando '
                   'houver sinais de gravidade.',
  'transcultural': {'preservacao': ['Reconhecer alimentos tradicionais leves e seguros.'],
                    'acomodacao': ['Orientar preparo seguro de água e alimentos.'],
                    'repadronizacao': ['Desestimular uso de antidiarreicos ou antibióticos sem prescrição.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dor lombar',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10039276', 'termo': 'Ensinar Exercício'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Dor lombar é comum por alterações posturais, ganho ponderal e frouxidão ligamentar. Deve-se '
                   'orientar postura, alongamentos seguros, repouso relativo, uso de calçados adequados e investigar '
                   'sinais urinários ou neurológicos.',
  'transcultural': {'preservacao': ['Valorizar práticas corporais seguras e aceitas pela gestante.'],
                    'acomodacao': ['Adaptar exercícios à rotina, trabalho e território.'],
                    'repadronizacao': ['Evitar massagens agressivas, automedicação e esforços excessivos.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dor pélvica',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Média',
  'fundamentacao': 'Dor pélvica pode estar associada a alterações musculoesqueléticas, crescimento uterino, infecção, '
                   'contrações ou sinais obstétricos. Deve-se avaliar intensidade, sangramento, perda de líquido, '
                   'febre e contrações.',
  'transcultural': {'preservacao': ['Acolher formas locais de descrever dor e desconforto.'],
                    'acomodacao': ['Orientar repouso, postura e sinais de alerta em linguagem acessível.'],
                    'repadronizacao': ['Reforçar busca imediata se houver sangramento, febre, perda de líquido ou '
                                       'contrações regulares.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dor abdominal',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Dor abdominal na gestação pode indicar condições benignas ou urgências obstétricas, como ameaça de '
                   'abortamento, trabalho de parto prematuro, descolamento placentário, infecção ou abdome agudo. '
                   'Deve-se avaliar sinais associados e encaminhar se dor intensa, persistente ou acompanhada de '
                   'sangramento, febre ou contrações.',
  'transcultural': {'preservacao': ['Acolher interpretações culturais da dor.'],
                    'acomodacao': ['Explicar sinais de risco para gestante e família.'],
                    'repadronizacao': ['Desencorajar atraso na busca de atendimento por uso exclusivo de remédios '
                                       'caseiros.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Cefaleia',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10044148', 'termo': 'Orientar sobre Medição de Pressão Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Cefaleia na gestação exige avaliação da pressão arterial e sinais de pré-eclâmpsia, especialmente '
                   'se intensa, persistente, associada a escotomas, dor epigástrica, edema ou proteinúria. A '
                   'enfermagem deve classificar risco e encaminhar quando necessário.',
  'transcultural': {'preservacao': ['Acolher medidas culturais seguras de conforto.'],
                    'acomodacao': ['Orientar sinais de alerta com linguagem clara.'],
                    'repadronizacao': ['Evitar automedicação e atraso na avaliação pressórica.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Tontura',
  'diagnostico': {'codigo': '10006160', 'termo': 'Tontura'},
  'resultado': {'codigo': '10028992', 'termo': 'Sintoma, Ausente'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Média',
  'fundamentacao': 'Tontura pode estar relacionada a hipotensão postural, hipoglicemia, anemia, desidratação ou '
                   'alterações clínicas. Deve-se avaliar sinais vitais, alimentação, hidratação, hemoglobina e '
                   'ocorrência de quedas ou síncope.',
  'transcultural': {'preservacao': ['Valorizar relatos da gestante sobre fatores desencadeantes.'],
                    'acomodacao': ['Orientar levantar lentamente, alimentar-se regularmente e hidratar-se.'],
                    'repadronizacao': ['Reforçar procura de atendimento se houver desmaio, palpitação, sangramento ou '
                                       'dor intensa.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Lipotímia',
  'diagnostico': {'codigo': '10006160', 'termo': 'Tontura'},
  'resultado': {'codigo': '10027617', 'termo': 'Equilíbrio Hídrico, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Lipotímia ou quase desmaio pode decorrer de hipotensão, hipoglicemia, anemia, arritmia, '
                   'desidratação ou sangramento. Exige avaliação de sinais vitais, glicemia quando disponível, '
                   'hidratação e encaminhamento se recorrente ou associada a sinais de risco.',
  'transcultural': {'preservacao': ['Acolher explicações familiares sobre o episódio.'],
                    'acomodacao': ['Orientar medidas imediatas de segurança para prevenir quedas.'],
                    'repadronizacao': ['Evitar normalizar desmaios recorrentes na gestação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dispneia',
  'diagnostico': {'codigo': '10006461', 'termo': 'Dispneia'},
  'resultado': {'codigo': '10029208', 'termo': 'Respiração, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Dispneia leve pode ocorrer por alterações fisiológicas da gestação, mas dispneia intensa, súbita, '
                   'associada a dor torácica, cianose, febre, taquicardia ou saturação baixa exige avaliação urgente.',
  'transcultural': {'preservacao': ['Acolher percepções culturais sobre falta de ar.'],
                    'acomodacao': ['Orientar repouso, posição confortável e sinais de alerta.'],
                    'repadronizacao': ['Reforçar que falta de ar importante não deve ser atribuída apenas à '
                                       'gravidez.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Edema fisiológico',
  'diagnostico': {'codigo': '10041951', 'termo': 'Edema'},
  'resultado': {'codigo': '10029019', 'termo': 'Edema, Reduzido'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Edema leve em membros inferiores pode ser fisiológico no final da gestação. Deve-se avaliar '
                   'pressão arterial, proteinúria e sinais de alarme. Orienta-se repouso com elevação de pernas, '
                   'hidratação e evitar longos períodos em pé.',
  'transcultural': {'preservacao': ['Valorizar práticas seguras de repouso e cuidado corporal.'],
                    'acomodacao': ['Adequar orientações à rotina laboral e doméstica.'],
                    'repadronizacao': ['Evitar uso de diuréticos, chás ou restrição hídrica sem prescrição.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Edema patológico',
  'diagnostico': {'codigo': '10041951', 'termo': 'Edema'},
  'resultado': {'codigo': '10029019', 'termo': 'Edema, Reduzido'},
  'intervencao': {'codigo': '10044148', 'termo': 'Orientar sobre Medição de Pressão Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Edema súbito, generalizado ou associado a hipertensão, cefaleia, alterações visuais, dor '
                   'epigástrica ou proteinúria pode indicar pré-eclâmpsia. Requer avaliação imediata e encaminhamento '
                   'conforme protocolo.',
  'transcultural': {'preservacao': ['Acolher o relato da gestante sobre mudanças corporais.'],
                    'acomodacao': ['Explicar sinais de gravidade para gestante e família.'],
                    'repadronizacao': ['Reforçar que edema no rosto e mãos, quando associado a sintomas, exige '
                                       'atendimento imediato.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Câimbras',
  'diagnostico': {'codigo': '10040943', 'termo': 'Cãibra Muscular'},
  'resultado': {'codigo': '10028337', 'termo': 'Conforto, Melhorado'},
  'intervencao': {'codigo': '10039276', 'termo': 'Ensinar Exercício'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Câimbras são comuns na gestação, especialmente em membros inferiores. Orienta-se alongamento '
                   'suave, hidratação, atividade física segura e avaliação se houver dor unilateral, edema importante '
                   'ou suspeita vascular.',
  'transcultural': {'preservacao': ['Manter práticas corporais seguras já utilizadas pela gestante.'],
                    'acomodacao': ['Adaptar alongamentos à capacidade física e idade gestacional.'],
                    'repadronizacao': ['Desencorajar uso de medicamentos ou suplementos sem avaliação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Fadiga',
  'diagnostico': {'codigo': '10000695', 'termo': 'Fadiga'},
  'resultado': {'codigo': '10000707', 'termo': 'Fadiga, Reduzida'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Fadiga pode ser fisiológica, mas também se relaciona a anemia, sono inadequado, sobrecarga de '
                   'trabalho, sofrimento emocional ou doença clínica. A enfermagem deve avaliar intensidade, rotina, '
                   'exames e sinais associados.',
  'transcultural': {'preservacao': ['Reconhecer papéis familiares e atividades culturais da gestante.'],
                    'acomodacao': ['Negociar pausas, divisão de tarefas e repouso possível.'],
                    'repadronizacao': ['Evitar naturalizar fadiga incapacitante sem investigação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Insônia',
  'diagnostico': {'codigo': '10010330', 'termo': 'Insônia'},
  'resultado': {'codigo': '10041399', 'termo': 'Sono, Melhorado'},
  'intervencao': {'codigo': '10024662', 'termo': 'Orientar sobre Sono'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Insônia pode ocorrer por desconfortos físicos, ansiedade, noctúria e alterações hormonais. Deve-se '
                   'orientar higiene do sono, posição confortável, rotina relaxante e avaliar sofrimento psíquico.',
  'transcultural': {'preservacao': ['Valorizar rituais culturais seguros de relaxamento.'],
                    'acomodacao': ['Adaptar medidas de sono à rotina familiar e ambiente domiciliar.'],
                    'repadronizacao': ['Evitar uso de sedativos, álcool ou fitoterápicos sem prescrição.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Sonolência',
  'diagnostico': {'codigo': '10041396', 'termo': 'Sono, Prejudicado'},
  'resultado': {'codigo': '10041399', 'termo': 'Sono, Melhorado'},
  'intervencao': {'codigo': '10024662', 'termo': 'Orientar sobre Sono'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Sonolência pode ser fisiológica no início da gestação, mas deve ser avaliada quando excessiva, '
                   'associada a anemia, depressão, privação de sono, uso de medicamentos ou prejuízo funcional.',
  'transcultural': {'preservacao': ['Respeitar hábitos familiares de descanso quando seguros.'],
                    'acomodacao': ['Orientar pausas programadas e rotina regular de sono.'],
                    'repadronizacao': ['Investigar sonolência incapacitante em vez de atribuí-la apenas à gestação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Corrimento vaginal',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Média',
  'fundamentacao': 'Corrimento vaginal pode ser fisiológico quando claro e sem odor, mas corrimento com odor, prurido, '
                   'dor, ardor ou alteração de cor sugere infecção vaginal ou IST. Deve-se avaliar sintomas associados '
                   'e encaminhar para diagnóstico e tratamento.',
  'transcultural': {'preservacao': ['Acolher crenças sobre higiene íntima sem julgamento.'],
                    'acomodacao': ['Orientar higiene adequada e uso de roupas confortáveis.'],
                    'repadronizacao': ['Desencorajar duchas vaginais, automedicação e uso de produtos irritantes.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Prurido vaginal',
  'diagnostico': {'codigo': '10023032', 'termo': 'Infecção'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Média',
  'fundamentacao': 'Prurido vaginal pode indicar candidíase, vaginose, IST ou irritação local. A gestante deve ser '
                   'avaliada para tratamento adequado, evitando automedicação e prevenindo complicações.',
  'transcultural': {'preservacao': ['Acolher pudor e formas culturais de relatar sintomas íntimos.'],
                    'acomodacao': ['Garantir privacidade e linguagem respeitosa.'],
                    'repadronizacao': ['Evitar uso de pomadas, duchas ou receitas caseiras sem avaliação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Sangramento vaginal',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10028120', 'termo': 'Sangramento, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sangramento vaginal na gestação é sinal de alerta e pode estar associado a abortamento, gravidez '
                   'ectópica, placenta prévia, descolamento placentário ou trabalho de parto. Exige avaliação '
                   'imediata, independentemente do volume.',
  'transcultural': {'preservacao': ['Acolher a gestante e reduzir medo e culpa.'],
                    'acomodacao': ['Orientar familiares sobre urgência do atendimento.'],
                    'repadronizacao': ['Reforçar que sangramento não deve ser observado em casa sem avaliação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Perda de líquido',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10028120', 'termo': 'Risco, Reduzido'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Perda de líquido vaginal pode indicar ruptura de membranas, com risco de infecção, prematuridade e '
                   'sofrimento fetal. Deve-se encaminhar imediatamente para avaliação obstétrica, evitando toque '
                   'vaginal desnecessário.',
  'transcultural': {'preservacao': ['Acolher a descrição da gestante sobre o líquido e circunstâncias.'],
                    'acomodacao': ['Explicar que perda contínua, mesmo sem dor, exige avaliação.'],
                    'repadronizacao': ['Evitar espera domiciliar ou uso de absorventes internos.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Redução dos movimentos fetais',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Redução ou ausência de movimentos fetais após a percepção habitual é sinal de alerta e pode '
                   'indicar comprometimento fetal. A gestante deve ser orientada a procurar avaliação imediata para '
                   'ausculta fetal e conduta obstétrica.',
  'transcultural': {'preservacao': ['Valorizar a percepção materna sobre o padrão de movimentos do bebê.'],
                    'acomodacao': ['Orientar registro e observação dos movimentos fetais conforme idade gestacional.'],
                    'repadronizacao': ['Desestimular esperar muitos dias para procurar atendimento quando houver '
                                       'redução importante.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Febre',
  'diagnostico': {'codigo': '10007916', 'termo': 'Febre'},
  'resultado': {'codigo': '10033694', 'termo': 'Temperatura Corporal, nos Limites Normais'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Febre na gestação pode indicar infecção urinária, respiratória, gastrointestinal, arbovirose, '
                   'infecção intra-amniótica ou outras condições de risco. Requer avaliação clínica, hidratação, '
                   'investigação etiológica e encaminhamento conforme gravidade.',
  'transcultural': {'preservacao': ['Acolher práticas culturais seguras de conforto térmico.'],
                    'acomodacao': ['Orientar hidratação e monitoramento da temperatura.'],
                    'repadronizacao': ['Evitar uso de medicamentos, chás ou banhos extremos sem orientação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Disúria',
  'diagnostico': {'codigo': '10029915', 'termo': 'Infecção do Trato Urinário'},
  'resultado': {'codigo': '10028945', 'termo': 'Infecção, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Alta',
  'fundamentacao': 'Disúria sugere infecção urinária, condição frequente na gestação e associada a pielonefrite, parto '
                   'prematuro e baixo peso ao nascer. Deve-se solicitar/avaliar exames conforme protocolo, orientar '
                   'hidratação e tratamento prescrito.',
  'transcultural': {'preservacao': ['Acolher práticas seguras de cuidado íntimo.'],
                    'acomodacao': ['Orientar ingestão hídrica e adesão ao tratamento.'],
                    'repadronizacao': ['Desestimular automedicação e interrupção precoce de antibiótico.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Polaciúria',
  'diagnostico': {'codigo': '10001359', 'termo': 'Função do Sistema Urinário, Prejudicada'},
  'resultado': {'codigo': '10028615', 'termo': 'Função do Sistema Urinário, Eficaz'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Média',
  'fundamentacao': 'Polaciúria pode ser fisiológica pela compressão uterina, mas quando associada a disúria, urgência, '
                   'febre ou dor lombar sugere infecção urinária. A enfermagem deve diferenciar sintomas fisiológicos '
                   'de sinais de infecção.',
  'transcultural': {'preservacao': ['Acolher relatos sobre hábitos urinários.'],
                    'acomodacao': ['Orientar sinais de alerta e hidratação adequada.'],
                    'repadronizacao': ['Evitar reduzir ingestão hídrica de forma inadequada por medo de urinar.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Urgência urinária',
  'diagnostico': {'codigo': '10001359', 'termo': 'Função do Sistema Urinário, Prejudicada'},
  'resultado': {'codigo': '10028615', 'termo': 'Função do Sistema Urinário, Eficaz'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre Infecção'},
  'prioridade': 'Média',
  'fundamentacao': 'Urgência urinária pode ocorrer por alterações mecânicas da gestação ou infecção urinária. Deve-se '
                   'investigar disúria, febre, dor lombar, hematúria e orientar coleta de exames e tratamento conforme '
                   'protocolo.',
  'transcultural': {'preservacao': ['Respeitar formas de expressão de sintomas urinários.'],
                    'acomodacao': ['Garantir privacidade para abordagem do sintoma.'],
                    'repadronizacao': ['Reforçar que urgência com dor ou febre precisa de avaliação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Incontinência urinária',
  'diagnostico': {'codigo': '10025686', 'termo': 'Incontinência Urinária'},
  'resultado': {'codigo': '10028615', 'termo': 'Função do Sistema Urinário, Eficaz'},
  'intervencao': {'codigo': '10039276', 'termo': 'Ensinar Exercício'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Incontinência urinária pode ocorrer por sobrecarga do assoalho pélvico durante a gestação. A '
                   'enfermagem deve orientar exercícios pélvicos quando indicados, higiene, prevenção de irritações e '
                   'avaliação de infecção associada.',
  'transcultural': {'preservacao': ['Acolher o sintoma sem constrangimento.'],
                    'acomodacao': ['Orientar exercícios de forma respeitosa e adequada à compreensão da gestante.'],
                    'repadronizacao': ['Reduzir vergonha e estimular relato do sintoma nas consultas.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Hemorroidas',
  'diagnostico': {'codigo': '10009118', 'termo': 'Hemorroida'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre Nutrição'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Hemorroidas são favorecidas por constipação, aumento da pressão venosa e esforço evacuatório. '
                   'Orienta-se dieta rica em fibras, hidratação, evitar esforço, higiene local e avaliação se '
                   'sangramento intenso ou dor persistente.',
  'transcultural': {'preservacao': ['Respeitar pudor e formas culturais de relatar sintomas anorretais.'],
                    'acomodacao': ['Orientar medidas alimentares possíveis no território.'],
                    'repadronizacao': ['Evitar pomadas, supositórios ou chás sem orientação.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Varizes',
  'diagnostico': {'codigo': '10020882', 'termo': 'Veia Varicosa'},
  'resultado': {'codigo': '10028379', 'termo': 'Processo do Sistema Circulatório, Positivo'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Varizes podem surgir ou piorar na gestação por alterações hormonais, compressão venosa e aumento '
                   'do volume circulante. Orienta-se evitar longos períodos em pé, elevar membros, atividade física '
                   'segura e observar sinais de trombose.',
  'transcultural': {'preservacao': ['Valorizar práticas seguras de repouso e cuidado com pernas.'],
                    'acomodacao': ['Adaptar orientações às atividades domésticas e laborais.'],
                    'repadronizacao': ['Orientar busca imediata se dor unilateral, calor, vermelhidão ou edema '
                                       'assimétrico.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Prurido cutâneo',
  'diagnostico': {'codigo': '10010934', 'termo': 'Prurido'},
  'resultado': {'codigo': '10028337', 'termo': 'Conforto, Melhorado'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime Terapêutico'},
  'prioridade': 'Média',
  'fundamentacao': 'Prurido cutâneo pode estar relacionado ao estiramento da pele, alergias, dermatoses gestacionais '
                   'ou colestase intra-hepática, especialmente quando intenso em palmas e plantas ou associado a '
                   'icterícia. Deve-se avaliar sinais de gravidade e encaminhar quando indicado.',
  'transcultural': {'preservacao': ['Acolher práticas seguras de hidratação da pele.'],
                    'acomodacao': ['Orientar produtos suaves e evitar irritantes.'],
                    'repadronizacao': ['Evitar uso de plantas, pomadas ou medicamentos sem avaliação, principalmente '
                                       'em prurido intenso.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Alterações mamárias',
  'diagnostico': {'codigo': '10003595', 'termo': 'Processo Mamário, Prejudicado'},
  'resultado': {'codigo': '10033682', 'termo': 'Processo Mamário, Eficaz'},
  'intervencao': {'codigo': '10033017', 'termo': 'Orientar sobre Amamentação'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Alterações mamárias como aumento de volume, sensibilidade, escurecimento areolar e colostro podem '
                   'ser fisiológicas. A consulta deve orientar preparo para amamentação, sinais de alerta e evitar '
                   'práticas prejudiciais às mamas.',
  'transcultural': {'preservacao': ['Valorizar experiências familiares positivas de amamentação.'],
                    'acomodacao': ['Adequar orientações às crenças e experiências da gestante.'],
                    'repadronizacao': ['Desencorajar preparo agressivo dos mamilos ou uso de produtos irritantes.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Mastalgia',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10033017', 'termo': 'Orientar sobre Amamentação'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Mastalgia é comum por alterações hormonais e crescimento mamário. Deve-se orientar sutiã adequado, '
                   'medidas de conforto e avaliação se houver febre, vermelhidão, nódulo, secreção purulenta ou dor '
                   'intensa.',
  'transcultural': {'preservacao': ['Acolher pudor e crenças sobre exposição das mamas.'],
                    'acomodacao': ['Garantir privacidade na avaliação e orientação.'],
                    'repadronizacao': ['Estimular procura de atendimento diante de sinais inflamatórios.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Contrações uterinas',
  'diagnostico': {'codigo': '10006364', 'termo': 'Contração Uterina'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Contrações uterinas devem ser avaliadas quanto à frequência, intensidade, dor, idade gestacional, '
                   'perda de líquido, sangramento e alteração dos movimentos fetais. Contrações regulares antes de 37 '
                   'semanas sugerem risco de trabalho de parto prematuro.',
  'transcultural': {'preservacao': ['Acolher a forma como a gestante diferencia dor, cólica e contração.'],
                    'acomodacao': ['Orientar observação da frequência e duração das contrações.'],
                    'repadronizacao': ['Reforçar que contrações regulares antes do termo exigem atendimento '
                                       'imediato.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'Pré-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Sinais de trabalho de parto prematuro',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de Lesão'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para Serviço de Saúde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sinais de trabalho de parto prematuro incluem contrações regulares antes de 37 semanas, dor lombar '
                   'persistente, pressão pélvica, cólicas, sangramento, alteração do corrimento ou perda de líquido. A '
                   'condição exige encaminhamento imediato para avaliação obstétrica e prevenção de complicações '
                   'neonatais.',
  'transcultural': {'preservacao': ['Valorizar a percepção da gestante sobre mudanças no corpo.'],
                    'acomodacao': ['Orientar plano de deslocamento rápido, considerando território e rede de apoio.'],
                    'repadronizacao': ['Evitar aguardar em casa quando houver sinais de prematuridade.']},
  'referencias': ['Ministério da Saúde.', 'OMS.', 'FEBRASGO.', 'COFEN Resolução nº 736/2024.', 'Leininger.']}]
