# Arquivo reconstruído automaticamente para o SAPE IA 2.0
# Linha de cuidado: Pré-natal

REGRAS = [{'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'HipertensÃ£o arterial',
  'diagnostico': {'codigo': None, 'termo': 'PressÃ£o arterial alterada'},
  'resultado': {'codigo': None, 'termo': 'PressÃ£o arterial controlada'},
  'intervencao': {'codigo': None, 'termo': 'Monitorar pressÃ£o arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'PressÃ£o arterial elevada na gestaÃ§Ã£o exige avaliaÃ§Ã£o de risco para sÃ\xadndromes '
                   'hipertensivas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Adequar monitoramento conforme acesso da gestante ao serviÃ§o.'],
                    'repadronizacao': ['Criar plano de urgÃªncia para sinais de prÃ©-eclÃ¢mpsia.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'ProteinÃºria',
  'diagnostico': {'codigo': None, 'termo': 'Risco de condiÃ§Ã£o hipertensiva na gestaÃ§Ã£o'},
  'resultado': {'codigo': None, 'termo': 'Risco reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Avaliar sinais de gravidade'},
  'prioridade': 'Alta',
  'fundamentacao': 'ProteinÃºria associada Ã\xa0 hipertensÃ£o pode indicar prÃ©-eclÃ¢mpsia.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Orientar sinais de alerta com linguagem adequada ao contexto cultural.'],
                    'repadronizacao': ['Encaminhar conforme risco e organizar transporte se necessÃ¡rio.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Cefaleia persistente',
  'diagnostico': {'codigo': None, 'termo': 'Risco de condiÃ§Ã£o hipertensiva na gestaÃ§Ã£o'},
  'resultado': {'codigo': None, 'termo': 'SeguranÃ§a materno-fetal preservada'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para avaliaÃ§Ã£o conforme protocolo de risco gestacional'},
  'prioridade': 'Alta',
  'fundamentacao': 'Cefaleia persistente pode ser sinal de gravidade em sÃ\xadndromes hipertensivas.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Verificar prÃ¡ticas locais de autocuidado jÃ¡ utilizadas.'],
                    'repadronizacao': ['Orientar procura imediata do serviÃ§o diante de piora ou sinais associados.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Escotomas visuais',
  'diagnostico': {'codigo': None, 'termo': 'Risco de condiÃ§Ã£o hipertensiva na gestaÃ§Ã£o'},
  'resultado': {'codigo': None, 'termo': 'SeguranÃ§a materno-fetal preservada'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para avaliaÃ§Ã£o imediata'},
  'prioridade': 'Alta',
  'fundamentacao': 'AlteraÃ§Ãµes visuais na gestaÃ§Ã£o sÃ£o sinais de alerta para agravamento hipertensivo.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Explicar a gravidade usando linguagem simples.'],
                    'repadronizacao': ['Priorizar remoÃ§Ã£o/encaminhamento mesmo diante de barreiras territoriais.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Edema importante',
  'diagnostico': {'codigo': None, 'termo': 'Risco de prÃ©-eclÃ¢mpsia'},
  'resultado': {'codigo': None, 'termo': 'Risco reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Avaliar pressÃ£o arterial e proteinÃºria'},
  'prioridade': 'Alta',
  'fundamentacao': 'Edema importante associado a outros sinais pode indicar agravamento clÃ\xadnico.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar percepÃ§Ã£o cultural sobre edema na gestaÃ§Ã£o.'],
                    'repadronizacao': ['ReforÃ§ar sinais de alerta e necessidade de avaliaÃ§Ã£o imediata.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Glicemia alterada',
  'diagnostico': {'codigo': None, 'termo': 'Risco de glicemia alterada'},
  'resultado': {'codigo': None, 'termo': 'Glicemia controlada'},
  'intervencao': {'codigo': None, 'termo': 'Orientar acompanhamento glicÃªmico conforme protocolo'},
  'prioridade': 'Alta',
  'fundamentacao': 'AlteraÃ§Ãµes glicÃªmicas na gestaÃ§Ã£o exigem rastreamento e acompanhamento de diabetes '
                   'gestacional.',
  'transcultural': {'preservacao': ['Reconhecer hÃ¡bitos alimentares regionais.'],
                    'acomodacao': ['Adaptar orientaÃ§Ã£o alimentar Ã\xa0 disponibilidade local de alimentos.'],
                    'repadronizacao': ['Reorganizar plano alimentar quando houver risco metabÃ³lico.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Diabetes gestacional',
  'diagnostico': {'codigo': None, 'termo': 'Glicemia alterada'},
  'resultado': {'codigo': None, 'termo': 'Glicemia controlada'},
  'intervencao': {'codigo': None, 'termo': 'Acompanhar controle glicÃªmico'},
  'prioridade': 'Alta',
  'fundamentacao': 'Diabetes gestacional requer acompanhamento contÃ\xadnuo para reduÃ§Ã£o de riscos materno-fetais.',
  'transcultural': {'preservacao': ['Valorizar prÃ¡ticas alimentares seguras da famÃ\xadlia.'],
                    'acomodacao': ['Negociar mudanÃ§as alimentares possÃ\xadveis no contexto socioeconÃ´mico.'],
                    'repadronizacao': ['Encaminhar e intensificar acompanhamento conforme risco.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Anemia',
  'diagnostico': {'codigo': None, 'termo': 'Hemoglobina diminuÃ\xadda'},
  'resultado': {'codigo': None, 'termo': 'Hemoglobina melhorada'},
  'intervencao': {'codigo': None, 'termo': 'Orientar suplementaÃ§Ã£o de ferro'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Anemia gestacional pode comprometer o bem-estar materno-fetal e deve ser acompanhada.',
  'transcultural': {'preservacao': ['Considerar alimentos regionais ricos em ferro.'],
                    'acomodacao': ['Orientar alimentaÃ§Ã£o conforme disponibilidade local.'],
                    'repadronizacao': ['ReforÃ§ar adesÃ£o Ã\xa0 suplementaÃ§Ã£o quando houver risco.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Obesidade',
  'diagnostico': {'codigo': None, 'termo': 'Peso corporal aumentado'},
  'resultado': {'codigo': None, 'termo': 'Peso corporal adequado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar alimentaÃ§Ã£o saudÃ¡vel'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Obesidade na gestaÃ§Ã£o aumenta risco de hipertensÃ£o, diabetes gestacional e complicaÃ§Ãµes '
                   'obstÃ©tricas.',
  'transcultural': {'preservacao': ['Reconhecer hÃ¡bitos alimentares familiares.'],
                    'acomodacao': ['Negociar mudanÃ§as possÃ\xadveis sem desconsiderar cultura alimentar.'],
                    'repadronizacao': ['Reorganizar plano alimentar e atividade fÃ\xadsica conforme risco.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Baixo peso',
  'diagnostico': {'codigo': None, 'termo': 'Peso corporal diminuÃ\xaddo'},
  'resultado': {'codigo': None, 'termo': 'Estado nutricional melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar alimentaÃ§Ã£o adequada'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Baixo peso gestacional pode estar associado a vulnerabilidade nutricional e risco fetal.',
  'transcultural': {'preservacao': ['Considerar alimentos culturalmente aceitos.'],
                    'acomodacao': ['Ajustar plano alimentar Ã\xa0 renda e disponibilidade local.'],
                    'repadronizacao': ['Articular apoio alimentar quando houver inseguranÃ§a alimentar.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Leininger.', 'PNAB.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Tabagismo',
  'diagnostico': {'codigo': None, 'termo': 'Comportamento de saÃºde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Comportamento de saÃºde melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar cessaÃ§Ã£o do tabagismo'},
  'prioridade': 'Alta',
  'fundamentacao': 'Tabagismo na gestaÃ§Ã£o aumenta risco de complicaÃ§Ãµes maternas e fetais.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Investigar contexto familiar e social do uso de tabaco.'],
                    'repadronizacao': ['Construir plano gradual de reduÃ§Ã£o e cessaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Uso de Ã¡lcool',
  'diagnostico': {'codigo': None, 'termo': 'Comportamento de saÃºde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Comportamento de saÃºde melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Orientar interrupÃ§Ã£o do uso de Ã¡lcool'},
  'prioridade': 'Alta',
  'fundamentacao': 'O uso de Ã¡lcool na gestaÃ§Ã£o representa risco para o desenvolvimento fetal.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Avaliar contexto social e familiar relacionado ao uso.'],
                    'repadronizacao': ['Encaminhar para rede de apoio quando houver uso persistente.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Uso de drogas',
  'diagnostico': {'codigo': None, 'termo': 'Comportamento de saÃºde prejudicado'},
  'resultado': {'codigo': None, 'termo': 'Comportamento de saÃºde melhorado'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para cuidado compartilhado em saÃºde mental'},
  'prioridade': 'Alta',
  'fundamentacao': 'Uso de substÃ¢ncias psicoativas na gestaÃ§Ã£o exige cuidado multiprofissional e reduÃ§Ã£o de '
                   'danos.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Realizar escuta qualificada sem julgamento.'],
                    'repadronizacao': ['Articular rede de saÃºde mental, assistÃªncia social e prÃ©-natal de alto '
                                       'risco.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Rede de AtenÃ§Ã£o Psicossocial.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Idade materna menor que 15 anos',
  'diagnostico': {'codigo': None, 'termo': 'Risco materno-fetal aumentado'},
  'resultado': {'codigo': None, 'termo': 'Risco materno-fetal reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Encaminhar para acompanhamento de prÃ©-natal de alto risco'},
  'prioridade': 'Alta',
  'fundamentacao': 'GestaÃ§Ã£o em adolescente muito jovem requer avaliaÃ§Ã£o ampliada de risco clÃ\xadnico, social e '
                   'familiar.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Avaliar apoio familiar, vÃ\xadnculo escolar e proteÃ§Ã£o social.'],
                    'repadronizacao': ['Acionar rede de proteÃ§Ã£o quando necessÃ¡rio.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'ECA.', 'COFEN 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Fatores de risco',
  'achado_clinico': 'Idade materna maior ou igual a 35 anos',
  'diagnostico': {'codigo': None, 'termo': 'Risco materno-fetal aumentado'},
  'resultado': {'codigo': None, 'termo': 'Risco materno-fetal reduzido'},
  'intervencao': {'codigo': None, 'termo': 'Avaliar fatores de risco gestacional'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Idade materna avanÃ§ada pode estar associada a maior risco obstÃ©trico e comorbidades.',
  'transcultural': {'preservacao': [],
                    'acomodacao': ['Considerar histÃ³ria reprodutiva, rede de apoio e expectativas familiares.'],
                    'repadronizacao': ['Intensificar acompanhamento se houver comorbidades.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'Manual de GestaÃ§Ã£o de Alto Risco.', 'Leininger.']}]
