# Arquivo reconstruído automaticamente para o SAPE IA 2.0
# Linha de cuidado: Pré-natal

REGRAS = [{'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'NÃ¡useas',
  'diagnostico': {'codigo': '10012453', 'termo': 'NÃ¡usea'},
  'resultado': {'codigo': '10028992', 'termo': 'NÃ¡usea, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre NutriÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'NÃ¡useas sÃ£o frequentes no primeiro trimestre, geralmente relacionadas a alteraÃ§Ãµes hormonais. '
                   'A avaliaÃ§Ã£o deve identificar intensidade, hidrataÃ§Ã£o, perda ponderal e impacto funcional, '
                   'orientando fracionamento alimentar, hidrataÃ§Ã£o e sinais de alerta.',
  'transcultural': {'preservacao': ['Valorizar prÃ¡ticas alimentares culturais seguras que aliviem nÃ¡useas.'],
                    'acomodacao': ['Adaptar horÃ¡rios e tipos de alimentos Ã\xa0 rotina e tolerÃ¢ncia da gestante.'],
                    'repadronizacao': ['Reorientar uso de chÃ¡s, ervas ou medicamentos sem avaliaÃ§Ã£o profissional.']},
  'referencias': ['MinistÃ©rio da SaÃºde. PrÃ©-natal de baixo risco.',
                  'OMS. RecomendaÃ§Ãµes sobre cuidados prÃ©-natais.',
                  'FEBRASGO. AssistÃªncia prÃ©-natal.',
                  'COFEN ResoluÃ§Ã£o nÂº 736/2024.',
                  'Leininger. Teoria Transcultural.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'VÃ´mitos',
  'diagnostico': {'codigo': '10020864', 'termo': 'VÃ´mito'},
  'resultado': {'codigo': '10029134', 'termo': 'VÃ´mito, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre NutriÃ§Ã£o'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'VÃ´mitos persistentes podem causar desidrataÃ§Ã£o, perda de peso e distÃºrbios '
                   'hidroeletrolÃ\xadticos. No prÃ©-natal, deve-se avaliar frequÃªncia, aceitaÃ§Ã£o oral, diurese, '
                   'sinais de desidrataÃ§Ã£o e necessidade de encaminhamento.',
  'transcultural': {'preservacao': ['Reconhecer alimentos culturalmente aceitos que melhorem a tolerÃ¢ncia oral.'],
                    'acomodacao': ['Orientar pequenas refeiÃ§Ãµes, lÃ\xadquidos em pequenos volumes e repouso apÃ³s '
                                   'alimentaÃ§Ã£o.'],
                    'repadronizacao': ['Desencorajar automedicaÃ§Ã£o antiemÃ©tica e prÃ¡ticas inseguras.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'HiperÃªmese gravÃ\xaddica',
  'diagnostico': {'codigo': '10020864', 'termo': 'VÃ´mito'},
  'resultado': {'codigo': '10027617', 'termo': 'EquilÃ\xadbrio HÃ\xaddrico, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'HiperÃªmese gravÃ\xaddica caracteriza-se por vÃ´mitos intensos, perda de peso, desidrataÃ§Ã£o, '
                   'cetonÃºria e risco de desequilÃ\xadbrio metabÃ³lico. Requer avaliaÃ§Ã£o imediata, hidrataÃ§Ã£o, '
                   'suporte clÃ\xadnico e possÃ\xadvel encaminhamento hospitalar.',
  'transcultural': {'preservacao': ['Acolher explicaÃ§Ãµes culturais da gestante sobre o mal-estar.'],
                    'acomodacao': ['Explicar sinais de gravidade de forma simples para gestante e famÃ\xadlia.'],
                    'repadronizacao': ['ReforÃ§ar que vÃ´mitos intensos nÃ£o devem ser tratados apenas com medidas '
                                       'caseiras.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Azia',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre NutriÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Azia Ã© comum na gestaÃ§Ã£o por relaxamento do esfÃ\xadncter esofÃ¡gico e compressÃ£o uterina. '
                   'Deve-se orientar refeiÃ§Ãµes menores, evitar deitar apÃ³s comer e observar sinais de alarme, como '
                   'dor intensa ou vÃ´mitos persistentes.',
  'transcultural': {'preservacao': ['Manter alimentos tradicionais que nÃ£o piorem sintomas.'],
                    'acomodacao': ['Ajustar orientaÃ§Ã£o alimentar Ã\xa0 rotina familiar.'],
                    'repadronizacao': ['Evitar automedicaÃ§Ã£o com antiÃ¡cidos ou bicarbonato sem orientaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Pirose',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre NutriÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Pirose gestacional geralmente decorre de refluxo gastroesofÃ¡gico. A enfermagem deve orientar '
                   'medidas posturais, fracionamento alimentar, reduÃ§Ã£o de alimentos irritantes e avaliaÃ§Ã£o se '
                   'sintomas forem intensos ou persistentes.',
  'transcultural': {'preservacao': ['Preservar preparaÃ§Ãµes alimentares locais bem toleradas.'],
                    'acomodacao': ['Negociar substituiÃ§Ãµes alimentares possÃ\xadveis.'],
                    'repadronizacao': ['Desestimular condutas caseiras de risco ou uso indiscriminado de '
                                       'medicamentos.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'ConstipaÃ§Ã£o',
  'diagnostico': {'codigo': '10004999', 'termo': 'ConstipaÃ§Ã£o'},
  'resultado': {'codigo': '10027800', 'termo': 'EliminaÃ§Ã£o Intestinal, Eficaz'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre NutriÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'ConstipaÃ§Ã£o Ã© frequente na gestaÃ§Ã£o por alteraÃ§Ãµes hormonais, reduÃ§Ã£o da motilidade '
                   'intestinal e suplementaÃ§Ã£o de ferro. Orienta-se aumento de fibras, ingestÃ£o hÃ\xaddrica, '
                   'atividade fÃ\xadsica se nÃ£o contraindicada e evitar laxantes sem prescriÃ§Ã£o.',
  'transcultural': {'preservacao': ['Valorizar alimentos regionais ricos em fibras.'],
                    'acomodacao': ['Adequar consumo de Ã¡gua e fibras Ã\xa0 disponibilidade local.'],
                    'repadronizacao': ['Evitar uso rotineiro de laxantes, chÃ¡s purgativos ou automedicaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Diarreia',
  'diagnostico': {'codigo': '10005933', 'termo': 'Diarreia'},
  'resultado': {'codigo': '10027800', 'termo': 'EliminaÃ§Ã£o Intestinal, Eficaz'},
  'intervencao': {'codigo': '10036112', 'termo': 'Orientar sobre HidrataÃ§Ã£o'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Diarreia pode causar desidrataÃ§Ã£o e indicar infecÃ§Ã£o gastrointestinal. A enfermagem deve '
                   'avaliar duraÃ§Ã£o, febre, sangue nas fezes, sinais de desidrataÃ§Ã£o, orientar hidrataÃ§Ã£o e '
                   'encaminhar quando houver sinais de gravidade.',
  'transcultural': {'preservacao': ['Reconhecer alimentos tradicionais leves e seguros.'],
                    'acomodacao': ['Orientar preparo seguro de Ã¡gua e alimentos.'],
                    'repadronizacao': ['Desestimular uso de antidiarreicos ou antibiÃ³ticos sem prescriÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dor lombar',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10039276', 'termo': 'Ensinar ExercÃ\xadcio'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Dor lombar Ã© comum por alteraÃ§Ãµes posturais, ganho ponderal e frouxidÃ£o ligamentar. Deve-se '
                   'orientar postura, alongamentos seguros, repouso relativo, uso de calÃ§ados adequados e investigar '
                   'sinais urinÃ¡rios ou neurolÃ³gicos.',
  'transcultural': {'preservacao': ['Valorizar prÃ¡ticas corporais seguras e aceitas pela gestante.'],
                    'acomodacao': ['Adaptar exercÃ\xadcios Ã\xa0 rotina, trabalho e territÃ³rio.'],
                    'repadronizacao': ['Evitar massagens agressivas, automedicaÃ§Ã£o e esforÃ§os excessivos.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dor pÃ©lvica',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Dor pÃ©lvica pode estar associada a alteraÃ§Ãµes musculoesquelÃ©ticas, crescimento uterino, '
                   'infecÃ§Ã£o, contraÃ§Ãµes ou sinais obstÃ©tricos. Deve-se avaliar intensidade, sangramento, perda '
                   'de lÃ\xadquido, febre e contraÃ§Ãµes.',
  'transcultural': {'preservacao': ['Acolher formas locais de descrever dor e desconforto.'],
                    'acomodacao': ['Orientar repouso, postura e sinais de alerta em linguagem acessÃ\xadvel.'],
                    'repadronizacao': ['ReforÃ§ar busca imediata se houver sangramento, febre, perda de lÃ\xadquido ou '
                                       'contraÃ§Ãµes regulares.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dor abdominal',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Dor abdominal na gestaÃ§Ã£o pode indicar condiÃ§Ãµes benignas ou urgÃªncias obstÃ©tricas, como '
                   'ameaÃ§a de abortamento, trabalho de parto prematuro, descolamento placentÃ¡rio, infecÃ§Ã£o ou '
                   'abdome agudo. Deve-se avaliar sinais associados e encaminhar se dor intensa, persistente ou '
                   'acompanhada de sangramento, febre ou contraÃ§Ãµes.',
  'transcultural': {'preservacao': ['Acolher interpretaÃ§Ãµes culturais da dor.'],
                    'acomodacao': ['Explicar sinais de risco para gestante e famÃ\xadlia.'],
                    'repadronizacao': ['Desencorajar atraso na busca de atendimento por uso exclusivo de remÃ©dios '
                                       'caseiros.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Cefaleia',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10044148', 'termo': 'Orientar sobre MediÃ§Ã£o de PressÃ£o Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Cefaleia na gestaÃ§Ã£o exige avaliaÃ§Ã£o da pressÃ£o arterial e sinais de prÃ©-eclÃ¢mpsia, '
                   'especialmente se intensa, persistente, associada a escotomas, dor epigÃ¡strica, edema ou '
                   'proteinÃºria. A enfermagem deve classificar risco e encaminhar quando necessÃ¡rio.',
  'transcultural': {'preservacao': ['Acolher medidas culturais seguras de conforto.'],
                    'acomodacao': ['Orientar sinais de alerta com linguagem clara.'],
                    'repadronizacao': ['Evitar automedicaÃ§Ã£o e atraso na avaliaÃ§Ã£o pressÃ³rica.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Tontura',
  'diagnostico': {'codigo': '10006160', 'termo': 'Tontura'},
  'resultado': {'codigo': '10028992', 'termo': 'Sintoma, Ausente'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Tontura pode estar relacionada a hipotensÃ£o postural, hipoglicemia, anemia, desidrataÃ§Ã£o ou '
                   'alteraÃ§Ãµes clÃ\xadnicas. Deve-se avaliar sinais vitais, alimentaÃ§Ã£o, hidrataÃ§Ã£o, hemoglobina '
                   'e ocorrÃªncia de quedas ou sÃ\xadncope.',
  'transcultural': {'preservacao': ['Valorizar relatos da gestante sobre fatores desencadeantes.'],
                    'acomodacao': ['Orientar levantar lentamente, alimentar-se regularmente e hidratar-se.'],
                    'repadronizacao': ['ReforÃ§ar procura de atendimento se houver desmaio, palpitaÃ§Ã£o, sangramento '
                                       'ou dor intensa.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'LipotÃ\xadmia',
  'diagnostico': {'codigo': '10006160', 'termo': 'Tontura'},
  'resultado': {'codigo': '10027617', 'termo': 'EquilÃ\xadbrio HÃ\xaddrico, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'LipotÃ\xadmia ou quase desmaio pode decorrer de hipotensÃ£o, hipoglicemia, anemia, arritmia, '
                   'desidrataÃ§Ã£o ou sangramento. Exige avaliaÃ§Ã£o de sinais vitais, glicemia quando disponÃ\xadvel, '
                   'hidrataÃ§Ã£o e encaminhamento se recorrente ou associada a sinais de risco.',
  'transcultural': {'preservacao': ['Acolher explicaÃ§Ãµes familiares sobre o episÃ³dio.'],
                    'acomodacao': ['Orientar medidas imediatas de seguranÃ§a para prevenir quedas.'],
                    'repadronizacao': ['Evitar normalizar desmaios recorrentes na gestaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Dispneia',
  'diagnostico': {'codigo': '10006461', 'termo': 'Dispneia'},
  'resultado': {'codigo': '10029208', 'termo': 'RespiraÃ§Ã£o, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Dispneia leve pode ocorrer por alteraÃ§Ãµes fisiolÃ³gicas da gestaÃ§Ã£o, mas dispneia intensa, '
                   'sÃºbita, associada a dor torÃ¡cica, cianose, febre, taquicardia ou saturaÃ§Ã£o baixa exige '
                   'avaliaÃ§Ã£o urgente.',
  'transcultural': {'preservacao': ['Acolher percepÃ§Ãµes culturais sobre falta de ar.'],
                    'acomodacao': ['Orientar repouso, posiÃ§Ã£o confortÃ¡vel e sinais de alerta.'],
                    'repadronizacao': ['ReforÃ§ar que falta de ar importante nÃ£o deve ser atribuÃ\xadda apenas Ã\xa0 '
                                       'gravidez.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Edema fisiolÃ³gico',
  'diagnostico': {'codigo': '10041951', 'termo': 'Edema'},
  'resultado': {'codigo': '10029019', 'termo': 'Edema, Reduzido'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Edema leve em membros inferiores pode ser fisiolÃ³gico no final da gestaÃ§Ã£o. Deve-se avaliar '
                   'pressÃ£o arterial, proteinÃºria e sinais de alarme. Orienta-se repouso com elevaÃ§Ã£o de pernas, '
                   'hidrataÃ§Ã£o e evitar longos perÃ\xadodos em pÃ©.',
  'transcultural': {'preservacao': ['Valorizar prÃ¡ticas seguras de repouso e cuidado corporal.'],
                    'acomodacao': ['Adequar orientaÃ§Ãµes Ã\xa0 rotina laboral e domÃ©stica.'],
                    'repadronizacao': ['Evitar uso de diurÃ©ticos, chÃ¡s ou restriÃ§Ã£o hÃ\xaddrica sem '
                                       'prescriÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Edema patolÃ³gico',
  'diagnostico': {'codigo': '10041951', 'termo': 'Edema'},
  'resultado': {'codigo': '10029019', 'termo': 'Edema, Reduzido'},
  'intervencao': {'codigo': '10044148', 'termo': 'Orientar sobre MediÃ§Ã£o de PressÃ£o Arterial'},
  'prioridade': 'Alta',
  'fundamentacao': 'Edema sÃºbito, generalizado ou associado a hipertensÃ£o, cefaleia, alteraÃ§Ãµes visuais, dor '
                   'epigÃ¡strica ou proteinÃºria pode indicar prÃ©-eclÃ¢mpsia. Requer avaliaÃ§Ã£o imediata e '
                   'encaminhamento conforme protocolo.',
  'transcultural': {'preservacao': ['Acolher o relato da gestante sobre mudanÃ§as corporais.'],
                    'acomodacao': ['Explicar sinais de gravidade para gestante e famÃ\xadlia.'],
                    'repadronizacao': ['ReforÃ§ar que edema no rosto e mÃ£os, quando associado a sintomas, exige '
                                       'atendimento imediato.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'CÃ¢imbras',
  'diagnostico': {'codigo': '10040943', 'termo': 'CÃ£ibra Muscular'},
  'resultado': {'codigo': '10028337', 'termo': 'Conforto, Melhorado'},
  'intervencao': {'codigo': '10039276', 'termo': 'Ensinar ExercÃ\xadcio'},
  'prioridade': 'Baixa',
  'fundamentacao': 'CÃ¢imbras sÃ£o comuns na gestaÃ§Ã£o, especialmente em membros inferiores. Orienta-se alongamento '
                   'suave, hidrataÃ§Ã£o, atividade fÃ\xadsica segura e avaliaÃ§Ã£o se houver dor unilateral, edema '
                   'importante ou suspeita vascular.',
  'transcultural': {'preservacao': ['Manter prÃ¡ticas corporais seguras jÃ¡ utilizadas pela gestante.'],
                    'acomodacao': ['Adaptar alongamentos Ã\xa0 capacidade fÃ\xadsica e idade gestacional.'],
                    'repadronizacao': ['Desencorajar uso de medicamentos ou suplementos sem avaliaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Fadiga',
  'diagnostico': {'codigo': '10000695', 'termo': 'Fadiga'},
  'resultado': {'codigo': '10000707', 'termo': 'Fadiga, Reduzida'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Fadiga pode ser fisiolÃ³gica, mas tambÃ©m se relaciona a anemia, sono inadequado, sobrecarga de '
                   'trabalho, sofrimento emocional ou doenÃ§a clÃ\xadnica. A enfermagem deve avaliar intensidade, '
                   'rotina, exames e sinais associados.',
  'transcultural': {'preservacao': ['Reconhecer papÃ©is familiares e atividades culturais da gestante.'],
                    'acomodacao': ['Negociar pausas, divisÃ£o de tarefas e repouso possÃ\xadvel.'],
                    'repadronizacao': ['Evitar naturalizar fadiga incapacitante sem investigaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'InsÃ´nia',
  'diagnostico': {'codigo': '10010330', 'termo': 'InsÃ´nia'},
  'resultado': {'codigo': '10041399', 'termo': 'Sono, Melhorado'},
  'intervencao': {'codigo': '10024662', 'termo': 'Orientar sobre Sono'},
  'prioridade': 'Baixa',
  'fundamentacao': 'InsÃ´nia pode ocorrer por desconfortos fÃ\xadsicos, ansiedade, noctÃºria e alteraÃ§Ãµes hormonais. '
                   'Deve-se orientar higiene do sono, posiÃ§Ã£o confortÃ¡vel, rotina relaxante e avaliar sofrimento '
                   'psÃ\xadquico.',
  'transcultural': {'preservacao': ['Valorizar rituais culturais seguros de relaxamento.'],
                    'acomodacao': ['Adaptar medidas de sono Ã\xa0 rotina familiar e ambiente domiciliar.'],
                    'repadronizacao': ['Evitar uso de sedativos, Ã¡lcool ou fitoterÃ¡picos sem prescriÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'SonolÃªncia',
  'diagnostico': {'codigo': '10041396', 'termo': 'Sono, Prejudicado'},
  'resultado': {'codigo': '10041399', 'termo': 'Sono, Melhorado'},
  'intervencao': {'codigo': '10024662', 'termo': 'Orientar sobre Sono'},
  'prioridade': 'Baixa',
  'fundamentacao': 'SonolÃªncia pode ser fisiolÃ³gica no inÃ\xadcio da gestaÃ§Ã£o, mas deve ser avaliada quando '
                   'excessiva, associada a anemia, depressÃ£o, privaÃ§Ã£o de sono, uso de medicamentos ou prejuÃ\xadzo '
                   'funcional.',
  'transcultural': {'preservacao': ['Respeitar hÃ¡bitos familiares de descanso quando seguros.'],
                    'acomodacao': ['Orientar pausas programadas e rotina regular de sono.'],
                    'repadronizacao': ['Investigar sonolÃªncia incapacitante em vez de atribuÃ\xad-la apenas Ã\xa0 '
                                       'gestaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Corrimento vaginal',
  'diagnostico': {'codigo': '10023032', 'termo': 'InfecÃ§Ã£o'},
  'resultado': {'codigo': '10028945', 'termo': 'InfecÃ§Ã£o, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre InfecÃ§Ã£o'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Corrimento vaginal pode ser fisiolÃ³gico quando claro e sem odor, mas corrimento com odor, '
                   'prurido, dor, ardor ou alteraÃ§Ã£o de cor sugere infecÃ§Ã£o vaginal ou IST. Deve-se avaliar '
                   'sintomas associados e encaminhar para diagnÃ³stico e tratamento.',
  'transcultural': {'preservacao': ['Acolher crenÃ§as sobre higiene Ã\xadntima sem julgamento.'],
                    'acomodacao': ['Orientar higiene adequada e uso de roupas confortÃ¡veis.'],
                    'repadronizacao': ['Desencorajar duchas vaginais, automedicaÃ§Ã£o e uso de produtos irritantes.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Prurido vaginal',
  'diagnostico': {'codigo': '10023032', 'termo': 'InfecÃ§Ã£o'},
  'resultado': {'codigo': '10028945', 'termo': 'InfecÃ§Ã£o, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre InfecÃ§Ã£o'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Prurido vaginal pode indicar candidÃ\xadase, vaginose, IST ou irritaÃ§Ã£o local. A gestante deve '
                   'ser avaliada para tratamento adequado, evitando automedicaÃ§Ã£o e prevenindo complicaÃ§Ãµes.',
  'transcultural': {'preservacao': ['Acolher pudor e formas culturais de relatar sintomas Ã\xadntimos.'],
                    'acomodacao': ['Garantir privacidade e linguagem respeitosa.'],
                    'repadronizacao': ['Evitar uso de pomadas, duchas ou receitas caseiras sem avaliaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Sangramento vaginal',
  'diagnostico': {'codigo': '10003303', 'termo': 'Sangramento'},
  'resultado': {'codigo': '10028120', 'termo': 'Sangramento, Ausente'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sangramento vaginal na gestaÃ§Ã£o Ã© sinal de alerta e pode estar associado a abortamento, '
                   'gravidez ectÃ³pica, placenta prÃ©via, descolamento placentÃ¡rio ou trabalho de parto. Exige '
                   'avaliaÃ§Ã£o imediata, independentemente do volume.',
  'transcultural': {'preservacao': ['Acolher a gestante e reduzir medo e culpa.'],
                    'acomodacao': ['Orientar familiares sobre urgÃªncia do atendimento.'],
                    'repadronizacao': ['ReforÃ§ar que sangramento nÃ£o deve ser observado em casa sem avaliaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Perda de lÃ\xadquido',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de LesÃ£o'},
  'resultado': {'codigo': '10028120', 'termo': 'Risco, Reduzido'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Perda de lÃ\xadquido vaginal pode indicar ruptura de membranas, com risco de infecÃ§Ã£o, '
                   'prematuridade e sofrimento fetal. Deve-se encaminhar imediatamente para avaliaÃ§Ã£o obstÃ©trica, '
                   'evitando toque vaginal desnecessÃ¡rio.',
  'transcultural': {'preservacao': ['Acolher a descriÃ§Ã£o da gestante sobre o lÃ\xadquido e circunstÃ¢ncias.'],
                    'acomodacao': ['Explicar que perda contÃ\xadnua, mesmo sem dor, exige avaliaÃ§Ã£o.'],
                    'repadronizacao': ['Evitar espera domiciliar ou uso de absorventes internos.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'ReduÃ§Ã£o dos movimentos fetais',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de LesÃ£o'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'ReduÃ§Ã£o ou ausÃªncia de movimentos fetais apÃ³s a percepÃ§Ã£o habitual Ã© sinal de alerta e pode '
                   'indicar comprometimento fetal. A gestante deve ser orientada a procurar avaliaÃ§Ã£o imediata para '
                   'ausculta fetal e conduta obstÃ©trica.',
  'transcultural': {'preservacao': ['Valorizar a percepÃ§Ã£o materna sobre o padrÃ£o de movimentos do bebÃª.'],
                    'acomodacao': ['Orientar registro e observaÃ§Ã£o dos movimentos fetais conforme idade '
                                   'gestacional.'],
                    'repadronizacao': ['Desestimular esperar muitos dias para procurar atendimento quando houver '
                                       'reduÃ§Ã£o importante.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Febre',
  'diagnostico': {'codigo': '10007916', 'termo': 'Febre'},
  'resultado': {'codigo': '10033694', 'termo': 'Temperatura Corporal, nos Limites Normais'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Febre na gestaÃ§Ã£o pode indicar infecÃ§Ã£o urinÃ¡ria, respiratÃ³ria, gastrointestinal, '
                   'arbovirose, infecÃ§Ã£o intra-amniÃ³tica ou outras condiÃ§Ãµes de risco. Requer avaliaÃ§Ã£o '
                   'clÃ\xadnica, hidrataÃ§Ã£o, investigaÃ§Ã£o etiolÃ³gica e encaminhamento conforme gravidade.',
  'transcultural': {'preservacao': ['Acolher prÃ¡ticas culturais seguras de conforto tÃ©rmico.'],
                    'acomodacao': ['Orientar hidrataÃ§Ã£o e monitoramento da temperatura.'],
                    'repadronizacao': ['Evitar uso de medicamentos, chÃ¡s ou banhos extremos sem orientaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'DisÃºria',
  'diagnostico': {'codigo': '10029915', 'termo': 'InfecÃ§Ã£o do Trato UrinÃ¡rio'},
  'resultado': {'codigo': '10028945', 'termo': 'InfecÃ§Ã£o, Ausente'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre InfecÃ§Ã£o'},
  'prioridade': 'Alta',
  'fundamentacao': 'DisÃºria sugere infecÃ§Ã£o urinÃ¡ria, condiÃ§Ã£o frequente na gestaÃ§Ã£o e associada a '
                   'pielonefrite, parto prematuro e baixo peso ao nascer. Deve-se solicitar/avaliar exames conforme '
                   'protocolo, orientar hidrataÃ§Ã£o e tratamento prescrito.',
  'transcultural': {'preservacao': ['Acolher prÃ¡ticas seguras de cuidado Ã\xadntimo.'],
                    'acomodacao': ['Orientar ingestÃ£o hÃ\xaddrica e adesÃ£o ao tratamento.'],
                    'repadronizacao': ['Desestimular automedicaÃ§Ã£o e interrupÃ§Ã£o precoce de antibiÃ³tico.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'PolaciÃºria',
  'diagnostico': {'codigo': '10001359', 'termo': 'FunÃ§Ã£o do Sistema UrinÃ¡rio, Prejudicada'},
  'resultado': {'codigo': '10028615', 'termo': 'FunÃ§Ã£o do Sistema UrinÃ¡rio, Eficaz'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'PolaciÃºria pode ser fisiolÃ³gica pela compressÃ£o uterina, mas quando associada a disÃºria, '
                   'urgÃªncia, febre ou dor lombar sugere infecÃ§Ã£o urinÃ¡ria. A enfermagem deve diferenciar sintomas '
                   'fisiolÃ³gicos de sinais de infecÃ§Ã£o.',
  'transcultural': {'preservacao': ['Acolher relatos sobre hÃ¡bitos urinÃ¡rios.'],
                    'acomodacao': ['Orientar sinais de alerta e hidrataÃ§Ã£o adequada.'],
                    'repadronizacao': ['Evitar reduzir ingestÃ£o hÃ\xaddrica de forma inadequada por medo de urinar.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'UrgÃªncia urinÃ¡ria',
  'diagnostico': {'codigo': '10001359', 'termo': 'FunÃ§Ã£o do Sistema UrinÃ¡rio, Prejudicada'},
  'resultado': {'codigo': '10028615', 'termo': 'FunÃ§Ã£o do Sistema UrinÃ¡rio, Eficaz'},
  'intervencao': {'codigo': '10051016', 'termo': 'Orientar sobre InfecÃ§Ã£o'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'UrgÃªncia urinÃ¡ria pode ocorrer por alteraÃ§Ãµes mecÃ¢nicas da gestaÃ§Ã£o ou infecÃ§Ã£o '
                   'urinÃ¡ria. Deve-se investigar disÃºria, febre, dor lombar, hematÃºria e orientar coleta de exames '
                   'e tratamento conforme protocolo.',
  'transcultural': {'preservacao': ['Respeitar formas de expressÃ£o de sintomas urinÃ¡rios.'],
                    'acomodacao': ['Garantir privacidade para abordagem do sintoma.'],
                    'repadronizacao': ['ReforÃ§ar que urgÃªncia com dor ou febre precisa de avaliaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'IncontinÃªncia urinÃ¡ria',
  'diagnostico': {'codigo': '10025686', 'termo': 'IncontinÃªncia UrinÃ¡ria'},
  'resultado': {'codigo': '10028615', 'termo': 'FunÃ§Ã£o do Sistema UrinÃ¡rio, Eficaz'},
  'intervencao': {'codigo': '10039276', 'termo': 'Ensinar ExercÃ\xadcio'},
  'prioridade': 'Baixa',
  'fundamentacao': 'IncontinÃªncia urinÃ¡ria pode ocorrer por sobrecarga do assoalho pÃ©lvico durante a gestaÃ§Ã£o. A '
                   'enfermagem deve orientar exercÃ\xadcios pÃ©lvicos quando indicados, higiene, prevenÃ§Ã£o de '
                   'irritaÃ§Ãµes e avaliaÃ§Ã£o de infecÃ§Ã£o associada.',
  'transcultural': {'preservacao': ['Acolher o sintoma sem constrangimento.'],
                    'acomodacao': ['Orientar exercÃ\xadcios de forma respeitosa e adequada Ã\xa0 compreensÃ£o da '
                                   'gestante.'],
                    'repadronizacao': ['Reduzir vergonha e estimular relato do sintoma nas consultas.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Hemorroidas',
  'diagnostico': {'codigo': '10009118', 'termo': 'Hemorroida'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10024618', 'termo': 'Orientar sobre NutriÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Hemorroidas sÃ£o favorecidas por constipaÃ§Ã£o, aumento da pressÃ£o venosa e esforÃ§o '
                   'evacuatÃ³rio. Orienta-se dieta rica em fibras, hidrataÃ§Ã£o, evitar esforÃ§o, higiene local e '
                   'avaliaÃ§Ã£o se sangramento intenso ou dor persistente.',
  'transcultural': {'preservacao': ['Respeitar pudor e formas culturais de relatar sintomas anorretais.'],
                    'acomodacao': ['Orientar medidas alimentares possÃ\xadveis no territÃ³rio.'],
                    'repadronizacao': ['Evitar pomadas, supositÃ³rios ou chÃ¡s sem orientaÃ§Ã£o.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Varizes',
  'diagnostico': {'codigo': '10020882', 'termo': 'Veia Varicosa'},
  'resultado': {'codigo': '10028379', 'termo': 'Processo do Sistema CirculatÃ³rio, Positivo'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Varizes podem surgir ou piorar na gestaÃ§Ã£o por alteraÃ§Ãµes hormonais, compressÃ£o venosa e '
                   'aumento do volume circulante. Orienta-se evitar longos perÃ\xadodos em pÃ©, elevar membros, '
                   'atividade fÃ\xadsica segura e observar sinais de trombose.',
  'transcultural': {'preservacao': ['Valorizar prÃ¡ticas seguras de repouso e cuidado com pernas.'],
                    'acomodacao': ['Adaptar orientaÃ§Ãµes Ã\xa0s atividades domÃ©sticas e laborais.'],
                    'repadronizacao': ['Orientar busca imediata se dor unilateral, calor, vermelhidÃ£o ou edema '
                                       'assimÃ©trico.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Prurido cutÃ¢neo',
  'diagnostico': {'codigo': '10010934', 'termo': 'Prurido'},
  'resultado': {'codigo': '10028337', 'termo': 'Conforto, Melhorado'},
  'intervencao': {'codigo': '10024625', 'termo': 'Orientar sobre Regime TerapÃªutico'},
  'prioridade': 'MÃ©dia',
  'fundamentacao': 'Prurido cutÃ¢neo pode estar relacionado ao estiramento da pele, alergias, dermatoses gestacionais '
                   'ou colestase intra-hepÃ¡tica, especialmente quando intenso em palmas e plantas ou associado a '
                   'icterÃ\xadcia. Deve-se avaliar sinais de gravidade e encaminhar quando indicado.',
  'transcultural': {'preservacao': ['Acolher prÃ¡ticas seguras de hidrataÃ§Ã£o da pele.'],
                    'acomodacao': ['Orientar produtos suaves e evitar irritantes.'],
                    'repadronizacao': ['Evitar uso de plantas, pomadas ou medicamentos sem avaliaÃ§Ã£o, principalmente '
                                       'em prurido intenso.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'AlteraÃ§Ãµes mamÃ¡rias',
  'diagnostico': {'codigo': '10003595', 'termo': 'Processo MamÃ¡rio, Prejudicado'},
  'resultado': {'codigo': '10033682', 'termo': 'Processo MamÃ¡rio, Eficaz'},
  'intervencao': {'codigo': '10033017', 'termo': 'Orientar sobre AmamentaÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'AlteraÃ§Ãµes mamÃ¡rias como aumento de volume, sensibilidade, escurecimento areolar e colostro '
                   'podem ser fisiolÃ³gicas. A consulta deve orientar preparo para amamentaÃ§Ã£o, sinais de alerta e '
                   'evitar prÃ¡ticas prejudiciais Ã\xa0s mamas.',
  'transcultural': {'preservacao': ['Valorizar experiÃªncias familiares positivas de amamentaÃ§Ã£o.'],
                    'acomodacao': ['Adequar orientaÃ§Ãµes Ã\xa0s crenÃ§as e experiÃªncias da gestante.'],
                    'repadronizacao': ['Desencorajar preparo agressivo dos mamilos ou uso de produtos irritantes.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Mastalgia',
  'diagnostico': {'codigo': '10013950', 'termo': 'Dor'},
  'resultado': {'codigo': '10029008', 'termo': 'Dor, Ausente'},
  'intervencao': {'codigo': '10033017', 'termo': 'Orientar sobre AmamentaÃ§Ã£o'},
  'prioridade': 'Baixa',
  'fundamentacao': 'Mastalgia Ã© comum por alteraÃ§Ãµes hormonais e crescimento mamÃ¡rio. Deve-se orientar sutiÃ£ '
                   'adequado, medidas de conforto e avaliaÃ§Ã£o se houver febre, vermelhidÃ£o, nÃ³dulo, secreÃ§Ã£o '
                   'purulenta ou dor intensa.',
  'transcultural': {'preservacao': ['Acolher pudor e crenÃ§as sobre exposiÃ§Ã£o das mamas.'],
                    'acomodacao': ['Garantir privacidade na avaliaÃ§Ã£o e orientaÃ§Ã£o.'],
                    'repadronizacao': ['Estimular procura de atendimento diante de sinais inflamatÃ³rios.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'ContraÃ§Ãµes uterinas',
  'diagnostico': {'codigo': '10006364', 'termo': 'ContraÃ§Ã£o Uterina'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'ContraÃ§Ãµes uterinas devem ser avaliadas quanto Ã\xa0 frequÃªncia, intensidade, dor, idade '
                   'gestacional, perda de lÃ\xadquido, sangramento e alteraÃ§Ã£o dos movimentos fetais. ContraÃ§Ãµes '
                   'regulares antes de 37 semanas sugerem risco de trabalho de parto prematuro.',
  'transcultural': {'preservacao': ['Acolher a forma como a gestante diferencia dor, cÃ³lica e contraÃ§Ã£o.'],
                    'acomodacao': ['Orientar observaÃ§Ã£o da frequÃªncia e duraÃ§Ã£o das contraÃ§Ãµes.'],
                    'repadronizacao': ['ReforÃ§ar que contraÃ§Ãµes regulares antes do termo exigem atendimento '
                                       'imediato.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']},
 {'linha_cuidado': 'PrÃ©-natal',
  'categoria': 'Sinais e sintomas',
  'achado_clinico': 'Sinais de trabalho de parto prematuro',
  'diagnostico': {'codigo': '10015146', 'termo': 'Risco de LesÃ£o'},
  'resultado': {'codigo': '10033682', 'termo': 'Estado Materno-Fetal, Eficaz'},
  'intervencao': {'codigo': '10035331', 'termo': 'Encaminhar para ServiÃ§o de SaÃºde'},
  'prioridade': 'Alta',
  'fundamentacao': 'Sinais de trabalho de parto prematuro incluem contraÃ§Ãµes regulares antes de 37 semanas, dor '
                   'lombar persistente, pressÃ£o pÃ©lvica, cÃ³licas, sangramento, alteraÃ§Ã£o do corrimento ou perda '
                   'de lÃ\xadquido. A condiÃ§Ã£o exige encaminhamento imediato para avaliaÃ§Ã£o obstÃ©trica e '
                   'prevenÃ§Ã£o de complicaÃ§Ãµes neonatais.',
  'transcultural': {'preservacao': ['Valorizar a percepÃ§Ã£o da gestante sobre mudanÃ§as no corpo.'],
                    'acomodacao': ['Orientar plano de deslocamento rÃ¡pido, considerando territÃ³rio e rede de apoio.'],
                    'repadronizacao': ['Evitar aguardar em casa quando houver sinais de prematuridade.']},
  'referencias': ['MinistÃ©rio da SaÃºde.', 'OMS.', 'FEBRASGO.', 'COFEN ResoluÃ§Ã£o nÂº 736/2024.', 'Leininger.']}]
